//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/miscellaneous/PrefixAndSuffixAwareTokenFilter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_INCLUDE_ALL")
#if OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_RESTRICT
#define OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_INCLUDE_ALL 0
#else
#define OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_RESTRICT

#if !defined (_OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_) && (OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_INCLUDE_ALL || OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_INCLUDE)
#define _OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_

#define OrgApacheLuceneAnalysisTokenStream_RESTRICT 1
#define OrgApacheLuceneAnalysisTokenStream_INCLUDE 1
#include "org/apache/lucene/analysis/TokenStream.h"

@class OrgApacheLuceneAnalysisToken;

@interface OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter : OrgApacheLuceneAnalysisTokenStream

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)prefix
                    withOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)input
                    withOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)suffix;

- (void)close;

- (void)end;

- (jboolean)incrementToken;

- (void)reset;

- (OrgApacheLuceneAnalysisToken *)updateInputTokenWithOrgApacheLuceneAnalysisToken:(OrgApacheLuceneAnalysisToken *)inputToken
                                                  withOrgApacheLuceneAnalysisToken:(OrgApacheLuceneAnalysisToken *)lastPrefixToken;

- (OrgApacheLuceneAnalysisToken *)updateSuffixTokenWithOrgApacheLuceneAnalysisToken:(OrgApacheLuceneAnalysisToken *)suffixToken
                                                   withOrgApacheLuceneAnalysisToken:(OrgApacheLuceneAnalysisToken *)lastInputToken;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter)

FOUNDATION_EXPORT void OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter *self, OrgApacheLuceneAnalysisTokenStream *prefix, OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisTokenStream *suffix);

FOUNDATION_EXPORT OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter *new_OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisTokenStream *prefix, OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisTokenStream *suffix) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter)

#endif

#pragma pop_macro("OrgApacheLuceneAnalysisMiscellaneousPrefixAndSuffixAwareTokenFilter_INCLUDE_ALL")
