//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/search/payloads/AveragePayloadFunction.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneSearchPayloadsAveragePayloadFunction_INCLUDE_ALL")
#if OrgApacheLuceneSearchPayloadsAveragePayloadFunction_RESTRICT
#define OrgApacheLuceneSearchPayloadsAveragePayloadFunction_INCLUDE_ALL 0
#else
#define OrgApacheLuceneSearchPayloadsAveragePayloadFunction_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneSearchPayloadsAveragePayloadFunction_RESTRICT

#if !defined (_OrgApacheLuceneSearchPayloadsAveragePayloadFunction_) && (OrgApacheLuceneSearchPayloadsAveragePayloadFunction_INCLUDE_ALL || OrgApacheLuceneSearchPayloadsAveragePayloadFunction_INCLUDE)
#define _OrgApacheLuceneSearchPayloadsAveragePayloadFunction_

#define OrgApacheLuceneSearchPayloadsPayloadFunction_RESTRICT 1
#define OrgApacheLuceneSearchPayloadsPayloadFunction_INCLUDE 1
#include "org/apache/lucene/search/payloads/PayloadFunction.h"

@interface OrgApacheLuceneSearchPayloadsAveragePayloadFunction : OrgApacheLuceneSearchPayloadsPayloadFunction

#pragma mark Public

- (instancetype)init;

- (jfloat)currentScoreWithInt:(jint)docId
                 withNSString:(NSString *)field
                      withInt:(jint)start
                      withInt:(jint)end
                      withInt:(jint)numPayloadsSeen
                    withFloat:(jfloat)currentScore
                    withFloat:(jfloat)currentPayloadScore;

- (jfloat)docScoreWithInt:(jint)docId
             withNSString:(NSString *)field
                  withInt:(jint)numPayloadsSeen
                withFloat:(jfloat)payloadScore;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchPayloadsAveragePayloadFunction)

FOUNDATION_EXPORT void OrgApacheLuceneSearchPayloadsAveragePayloadFunction_init(OrgApacheLuceneSearchPayloadsAveragePayloadFunction *self);

FOUNDATION_EXPORT OrgApacheLuceneSearchPayloadsAveragePayloadFunction *new_OrgApacheLuceneSearchPayloadsAveragePayloadFunction_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchPayloadsAveragePayloadFunction)

#endif

#pragma pop_macro("OrgApacheLuceneSearchPayloadsAveragePayloadFunction_INCLUDE_ALL")
