//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/ar/ArabicStemFilterFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneAnalysisArArabicStemFilterFactory_INCLUDE_ALL")
#if OrgApacheLuceneAnalysisArArabicStemFilterFactory_RESTRICT
#define OrgApacheLuceneAnalysisArArabicStemFilterFactory_INCLUDE_ALL 0
#else
#define OrgApacheLuceneAnalysisArArabicStemFilterFactory_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneAnalysisArArabicStemFilterFactory_RESTRICT

#if !defined (_OrgApacheLuceneAnalysisArArabicStemFilterFactory_) && (OrgApacheLuceneAnalysisArArabicStemFilterFactory_INCLUDE_ALL || OrgApacheLuceneAnalysisArArabicStemFilterFactory_INCLUDE)
#define _OrgApacheLuceneAnalysisArArabicStemFilterFactory_

#define OrgApacheLuceneAnalysisUtilTokenFilterFactory_RESTRICT 1
#define OrgApacheLuceneAnalysisUtilTokenFilterFactory_INCLUDE 1
#include "org/apache/lucene/analysis/util/TokenFilterFactory.h"

@class OrgApacheLuceneAnalysisArArabicStemFilter;
@class OrgApacheLuceneAnalysisTokenStream;
@protocol JavaUtilMap;

@interface OrgApacheLuceneAnalysisArArabicStemFilterFactory : OrgApacheLuceneAnalysisUtilTokenFilterFactory

#pragma mark Public

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)args;

- (OrgApacheLuceneAnalysisArArabicStemFilter *)createWithOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)input;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisArArabicStemFilterFactory)

FOUNDATION_EXPORT void OrgApacheLuceneAnalysisArArabicStemFilterFactory_initWithJavaUtilMap_(OrgApacheLuceneAnalysisArArabicStemFilterFactory *self, id<JavaUtilMap> args);

FOUNDATION_EXPORT OrgApacheLuceneAnalysisArArabicStemFilterFactory *new_OrgApacheLuceneAnalysisArArabicStemFilterFactory_initWithJavaUtilMap_(id<JavaUtilMap> args) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneAnalysisArArabicStemFilterFactory)

#endif

#pragma pop_macro("OrgApacheLuceneAnalysisArArabicStemFilterFactory_INCLUDE_ALL")
