//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/index/BufferedUpdates.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneIndexBufferedUpdates")
#ifdef RESTRICT_OrgApacheLuceneIndexBufferedUpdates
#define INCLUDE_ALL_OrgApacheLuceneIndexBufferedUpdates 0
#else
#define INCLUDE_ALL_OrgApacheLuceneIndexBufferedUpdates 1
#endif
#undef RESTRICT_OrgApacheLuceneIndexBufferedUpdates

#if !defined (OrgApacheLuceneIndexBufferedUpdates_) && (INCLUDE_ALL_OrgApacheLuceneIndexBufferedUpdates || defined(INCLUDE_OrgApacheLuceneIndexBufferedUpdates))
#define OrgApacheLuceneIndexBufferedUpdates_

@class JavaLangInteger;
@class JavaUtilConcurrentAtomicAtomicInteger;
@class JavaUtilConcurrentAtomicAtomicLong;
@class OrgApacheLuceneIndexDocValuesUpdate_BinaryDocValuesUpdate;
@class OrgApacheLuceneIndexDocValuesUpdate_NumericDocValuesUpdate;
@class OrgApacheLuceneIndexTerm;
@class OrgApacheLuceneSearchQuery;
@protocol JavaUtilList;
@protocol JavaUtilMap;

@interface OrgApacheLuceneIndexBufferedUpdates : NSObject {
 @public
  JavaUtilConcurrentAtomicAtomicInteger *numTermDeletes_;
  JavaUtilConcurrentAtomicAtomicInteger *numNumericUpdates_;
  JavaUtilConcurrentAtomicAtomicInteger *numBinaryUpdates_;
  id<JavaUtilMap> terms_;
  id<JavaUtilMap> queries_;
  id<JavaUtilList> docIDs_;
  id<JavaUtilMap> numericUpdates_;
  id<JavaUtilMap> binaryUpdates_;
  JavaUtilConcurrentAtomicAtomicLong *bytesUsed_;
  jlong gen_;
}

+ (jint)BYTES_PER_DEL_TERM;

+ (jint)BYTES_PER_DEL_DOCID;

+ (jint)BYTES_PER_DEL_QUERY;

+ (jint)BYTES_PER_NUMERIC_FIELD_ENTRY;

+ (jint)BYTES_PER_NUMERIC_UPDATE_ENTRY;

+ (jint)BYTES_PER_BINARY_FIELD_ENTRY;

+ (jint)BYTES_PER_BINARY_UPDATE_ENTRY;

+ (JavaLangInteger *)MAX_INT;

#pragma mark Public

- (instancetype)init;

- (void)addBinaryUpdateWithOrgApacheLuceneIndexDocValuesUpdate_BinaryDocValuesUpdate:(OrgApacheLuceneIndexDocValuesUpdate_BinaryDocValuesUpdate *)update
                                                                             withInt:(jint)docIDUpto;

- (void)addDocIDWithInt:(jint)docID;

- (void)addNumericUpdateWithOrgApacheLuceneIndexDocValuesUpdate_NumericDocValuesUpdate:(OrgApacheLuceneIndexDocValuesUpdate_NumericDocValuesUpdate *)update
                                                                               withInt:(jint)docIDUpto;

- (void)addQueryWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
                                       withInt:(jint)docIDUpto;

- (void)addTermWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term
                                    withInt:(jint)docIDUpto;

- (NSString *)description;

#pragma mark Package-Private

- (jboolean)any;

- (void)clear;

@end

J2OBJC_STATIC_INIT(OrgApacheLuceneIndexBufferedUpdates)

J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexBufferedUpdates, numTermDeletes_, JavaUtilConcurrentAtomicAtomicInteger *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexBufferedUpdates, numNumericUpdates_, JavaUtilConcurrentAtomicAtomicInteger *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexBufferedUpdates, numBinaryUpdates_, JavaUtilConcurrentAtomicAtomicInteger *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexBufferedUpdates, terms_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexBufferedUpdates, queries_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexBufferedUpdates, docIDs_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexBufferedUpdates, numericUpdates_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexBufferedUpdates, binaryUpdates_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexBufferedUpdates, bytesUsed_, JavaUtilConcurrentAtomicAtomicLong *)

inline jint OrgApacheLuceneIndexBufferedUpdates_get_BYTES_PER_DEL_TERM();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint OrgApacheLuceneIndexBufferedUpdates_BYTES_PER_DEL_TERM;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(OrgApacheLuceneIndexBufferedUpdates, BYTES_PER_DEL_TERM, jint)

inline jint OrgApacheLuceneIndexBufferedUpdates_get_BYTES_PER_DEL_DOCID();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint OrgApacheLuceneIndexBufferedUpdates_BYTES_PER_DEL_DOCID;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(OrgApacheLuceneIndexBufferedUpdates, BYTES_PER_DEL_DOCID, jint)

inline jint OrgApacheLuceneIndexBufferedUpdates_get_BYTES_PER_DEL_QUERY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint OrgApacheLuceneIndexBufferedUpdates_BYTES_PER_DEL_QUERY;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(OrgApacheLuceneIndexBufferedUpdates, BYTES_PER_DEL_QUERY, jint)

inline jint OrgApacheLuceneIndexBufferedUpdates_get_BYTES_PER_NUMERIC_FIELD_ENTRY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint OrgApacheLuceneIndexBufferedUpdates_BYTES_PER_NUMERIC_FIELD_ENTRY;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(OrgApacheLuceneIndexBufferedUpdates, BYTES_PER_NUMERIC_FIELD_ENTRY, jint)

inline jint OrgApacheLuceneIndexBufferedUpdates_get_BYTES_PER_NUMERIC_UPDATE_ENTRY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint OrgApacheLuceneIndexBufferedUpdates_BYTES_PER_NUMERIC_UPDATE_ENTRY;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(OrgApacheLuceneIndexBufferedUpdates, BYTES_PER_NUMERIC_UPDATE_ENTRY, jint)

inline jint OrgApacheLuceneIndexBufferedUpdates_get_BYTES_PER_BINARY_FIELD_ENTRY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint OrgApacheLuceneIndexBufferedUpdates_BYTES_PER_BINARY_FIELD_ENTRY;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(OrgApacheLuceneIndexBufferedUpdates, BYTES_PER_BINARY_FIELD_ENTRY, jint)

inline jint OrgApacheLuceneIndexBufferedUpdates_get_BYTES_PER_BINARY_UPDATE_ENTRY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint OrgApacheLuceneIndexBufferedUpdates_BYTES_PER_BINARY_UPDATE_ENTRY;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(OrgApacheLuceneIndexBufferedUpdates, BYTES_PER_BINARY_UPDATE_ENTRY, jint)

inline JavaLangInteger *OrgApacheLuceneIndexBufferedUpdates_get_MAX_INT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT JavaLangInteger *OrgApacheLuceneIndexBufferedUpdates_MAX_INT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheLuceneIndexBufferedUpdates, MAX_INT, JavaLangInteger *)

FOUNDATION_EXPORT void OrgApacheLuceneIndexBufferedUpdates_init(OrgApacheLuceneIndexBufferedUpdates *self);

FOUNDATION_EXPORT OrgApacheLuceneIndexBufferedUpdates *new_OrgApacheLuceneIndexBufferedUpdates_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneIndexBufferedUpdates *create_OrgApacheLuceneIndexBufferedUpdates_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexBufferedUpdates)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneIndexBufferedUpdates")
