//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/index/IndexReader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneIndexIndexReader_INCLUDE_ALL")
#if OrgApacheLuceneIndexIndexReader_RESTRICT
#define OrgApacheLuceneIndexIndexReader_INCLUDE_ALL 0
#else
#define OrgApacheLuceneIndexIndexReader_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneIndexIndexReader_RESTRICT

#if !defined (_OrgApacheLuceneIndexIndexReader_) && (OrgApacheLuceneIndexIndexReader_INCLUDE_ALL || OrgApacheLuceneIndexIndexReader_INCLUDE)
#define _OrgApacheLuceneIndexIndexReader_

#define JavaIoCloseable_RESTRICT 1
#define JavaIoCloseable_INCLUDE 1
#include "java/io/Closeable.h"

@class OrgApacheLuceneDocumentDocument;
@class OrgApacheLuceneIndexFields;
@class OrgApacheLuceneIndexIndexReaderContext;
@class OrgApacheLuceneIndexStoredFieldVisitor;
@class OrgApacheLuceneIndexTerm;
@protocol JavaUtilList;
@protocol JavaUtilSet;

@interface OrgApacheLuceneIndexIndexReader : NSObject < JavaIoCloseable >

#pragma mark Public

- (void)close;

- (void)decRef;

- (jint)docFreqWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term;

- (OrgApacheLuceneDocumentDocument *)documentWithInt:(jint)docID;

- (OrgApacheLuceneDocumentDocument *)documentWithInt:(jint)docID
                                     withJavaUtilSet:(id<JavaUtilSet>)fieldsToLoad;

- (void)documentWithInt:(jint)docID
withOrgApacheLuceneIndexStoredFieldVisitor:(OrgApacheLuceneIndexStoredFieldVisitor *)visitor;

- (jboolean)isEqual:(id)obj;

- (OrgApacheLuceneIndexIndexReaderContext *)getContext;

- (id)getCoreCacheKey;

- (jint)getRefCount;

- (OrgApacheLuceneIndexFields *)getTermVectorsWithInt:(jint)docID;

- (jboolean)hasDeletions;

- (NSUInteger)hash;

- (void)incRef;

- (id<JavaUtilList>)leaves;

- (jint)maxDoc;

- (jint)numDeletedDocs;

- (jint)numDocs;

- (void)registerParentReaderWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

- (jboolean)tryIncRef;

#pragma mark Protected

- (void)doClose;

- (void)ensureOpen;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexIndexReader)

FOUNDATION_EXPORT void OrgApacheLuceneIndexIndexReader_init(OrgApacheLuceneIndexIndexReader *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexIndexReader)

#endif

#if !defined (_OrgApacheLuceneIndexIndexReader_ReaderClosedListener_) && (OrgApacheLuceneIndexIndexReader_INCLUDE_ALL || OrgApacheLuceneIndexIndexReader_ReaderClosedListener_INCLUDE)
#define _OrgApacheLuceneIndexIndexReader_ReaderClosedListener_

@class OrgApacheLuceneIndexIndexReader;

@protocol OrgApacheLuceneIndexIndexReader_ReaderClosedListener < NSObject, JavaObject >

- (void)onCloseWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexIndexReader_ReaderClosedListener)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexIndexReader_ReaderClosedListener)

#endif

#pragma pop_macro("OrgApacheLuceneIndexIndexReader_INCLUDE_ALL")
