//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/index/SerialMergeScheduler.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneIndexSerialMergeScheduler_INCLUDE_ALL")
#if OrgApacheLuceneIndexSerialMergeScheduler_RESTRICT
#define OrgApacheLuceneIndexSerialMergeScheduler_INCLUDE_ALL 0
#else
#define OrgApacheLuceneIndexSerialMergeScheduler_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneIndexSerialMergeScheduler_RESTRICT

#if !defined (_OrgApacheLuceneIndexSerialMergeScheduler_) && (OrgApacheLuceneIndexSerialMergeScheduler_INCLUDE_ALL || OrgApacheLuceneIndexSerialMergeScheduler_INCLUDE)
#define _OrgApacheLuceneIndexSerialMergeScheduler_

#define OrgApacheLuceneIndexMergeScheduler_RESTRICT 1
#define OrgApacheLuceneIndexMergeScheduler_INCLUDE 1
#include "org/apache/lucene/index/MergeScheduler.h"

@class OrgApacheLuceneIndexIndexWriter;
@class OrgApacheLuceneIndexMergeTriggerEnum;

@interface OrgApacheLuceneIndexSerialMergeScheduler : OrgApacheLuceneIndexMergeScheduler

#pragma mark Public

- (instancetype)init;

- (void)close;

- (void)mergeWithOrgApacheLuceneIndexIndexWriter:(OrgApacheLuceneIndexIndexWriter *)writer
        withOrgApacheLuceneIndexMergeTriggerEnum:(OrgApacheLuceneIndexMergeTriggerEnum *)trigger
                                     withBoolean:(jboolean)newMergesFound;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexSerialMergeScheduler)

FOUNDATION_EXPORT void OrgApacheLuceneIndexSerialMergeScheduler_init(OrgApacheLuceneIndexSerialMergeScheduler *self);

FOUNDATION_EXPORT OrgApacheLuceneIndexSerialMergeScheduler *new_OrgApacheLuceneIndexSerialMergeScheduler_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexSerialMergeScheduler)

#endif

#pragma pop_macro("OrgApacheLuceneIndexSerialMergeScheduler_INCLUDE_ALL")
