//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/util/packed/BulkOperationPacked21.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneUtilPackedBulkOperationPacked21")
#ifdef RESTRICT_OrgApacheLuceneUtilPackedBulkOperationPacked21
#define INCLUDE_ALL_OrgApacheLuceneUtilPackedBulkOperationPacked21 0
#else
#define INCLUDE_ALL_OrgApacheLuceneUtilPackedBulkOperationPacked21 1
#endif
#undef RESTRICT_OrgApacheLuceneUtilPackedBulkOperationPacked21

#if !defined (OrgApacheLuceneUtilPackedBulkOperationPacked21_) && (INCLUDE_ALL_OrgApacheLuceneUtilPackedBulkOperationPacked21 || defined(INCLUDE_OrgApacheLuceneUtilPackedBulkOperationPacked21))
#define OrgApacheLuceneUtilPackedBulkOperationPacked21_

#define RESTRICT_OrgApacheLuceneUtilPackedBulkOperationPacked 1
#define INCLUDE_OrgApacheLuceneUtilPackedBulkOperationPacked 1
#include "org/apache/lucene/util/packed/BulkOperationPacked.h"

@class IOSByteArray;
@class IOSIntArray;
@class IOSLongArray;

/*!
 @brief Efficient sequential read/write of packed integers.
 */
@interface OrgApacheLuceneUtilPackedBulkOperationPacked21 : OrgApacheLuceneUtilPackedBulkOperationPacked

#pragma mark Public

- (instancetype)init;

- (void)decodeWithByteArray:(IOSByteArray *)blocks
                    withInt:(jint)blocksOffset
               withIntArray:(IOSIntArray *)values
                    withInt:(jint)valuesOffset
                    withInt:(jint)iterations;

- (void)decodeWithByteArray:(IOSByteArray *)blocks
                    withInt:(jint)blocksOffset
              withLongArray:(IOSLongArray *)values
                    withInt:(jint)valuesOffset
                    withInt:(jint)iterations;

- (void)decodeWithLongArray:(IOSLongArray *)blocks
                    withInt:(jint)blocksOffset
               withIntArray:(IOSIntArray *)values
                    withInt:(jint)valuesOffset
                    withInt:(jint)iterations;

- (void)decodeWithLongArray:(IOSLongArray *)blocks
                    withInt:(jint)blocksOffset
              withLongArray:(IOSLongArray *)values
                    withInt:(jint)valuesOffset
                    withInt:(jint)iterations;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneUtilPackedBulkOperationPacked21)

FOUNDATION_EXPORT void OrgApacheLuceneUtilPackedBulkOperationPacked21_init(OrgApacheLuceneUtilPackedBulkOperationPacked21 *self);

FOUNDATION_EXPORT OrgApacheLuceneUtilPackedBulkOperationPacked21 *new_OrgApacheLuceneUtilPackedBulkOperationPacked21_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneUtilPackedBulkOperationPacked21 *create_OrgApacheLuceneUtilPackedBulkOperationPacked21_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneUtilPackedBulkOperationPacked21)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneUtilPackedBulkOperationPacked21")
