//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/analysis/tokenattributes/PositionLengthAttribute.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/analysis/tokenattributes/PositionLengthAttribute.h"

@interface OrgApacheLuceneAnalysisTokenattributesPositionLengthAttribute : NSObject

@end

@implementation OrgApacheLuceneAnalysisTokenattributesPositionLengthAttribute

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setPositionLengthWithInt:", "setPositionLength", "V", 0x401, NULL, NULL },
    { "getPositionLength", NULL, "I", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisTokenattributesPositionLengthAttribute = { 2, "PositionLengthAttribute", "org.apache.lucene.analysis.tokenattributes", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneAnalysisTokenattributesPositionLengthAttribute;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisTokenattributesPositionLengthAttribute)
