//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/codecs/PostingsReaderBase.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneCodecsPostingsReaderBase")
#ifdef RESTRICT_OrgApacheLuceneCodecsPostingsReaderBase
#define INCLUDE_ALL_OrgApacheLuceneCodecsPostingsReaderBase 0
#else
#define INCLUDE_ALL_OrgApacheLuceneCodecsPostingsReaderBase 1
#endif
#undef RESTRICT_OrgApacheLuceneCodecsPostingsReaderBase

#if !defined (OrgApacheLuceneCodecsPostingsReaderBase_) && (INCLUDE_ALL_OrgApacheLuceneCodecsPostingsReaderBase || defined(INCLUDE_OrgApacheLuceneCodecsPostingsReaderBase))
#define OrgApacheLuceneCodecsPostingsReaderBase_

#define RESTRICT_JavaIoCloseable 1
#define INCLUDE_JavaIoCloseable 1
#include "java/io/Closeable.h"

#define RESTRICT_OrgApacheLuceneUtilAccountable 1
#define INCLUDE_OrgApacheLuceneUtilAccountable 1
#include "org/apache/lucene/util/Accountable.h"

@class IOSLongArray;
@class OrgApacheLuceneCodecsBlockTermState;
@class OrgApacheLuceneIndexFieldInfo;
@class OrgApacheLuceneIndexPostingsEnum;
@class OrgApacheLuceneIndexSegmentReadState;
@class OrgApacheLuceneStoreDataInput;
@class OrgApacheLuceneStoreIndexInput;

/*!
 @brief The core terms dictionaries (BlockTermsReader,
 BlockTreeTermsReader) interact with a single instance
 of this class to manage creation of <code>org.apache.lucene.index.PostingsEnum</code> and
 <code>org.apache.lucene.index.PostingsEnum</code> instances.
 It provides an
 IndexInput (termsIn) where this class may read any
 previously stored data that it had written in its
 corresponding <code>PostingsWriterBase</code> at indexing
 time. 
  
 */
@interface OrgApacheLuceneCodecsPostingsReaderBase : NSObject < JavaIoCloseable, OrgApacheLuceneUtilAccountable >

#pragma mark Public

/*!
 @brief Checks consistency of this reader.
 <p>
 Note that this may be costly in terms of I/O, e.g. 
 may involve computing a checksum value against large data files.
 */
- (void)checkIntegrity;

- (void)close;

/*!
 @brief Actually decode metadata for next term
 - seealso: PostingsWriterBase#encodeTerm
 */
- (void)decodeTermWithLongArray:(IOSLongArray *)longs
withOrgApacheLuceneStoreDataInput:(OrgApacheLuceneStoreDataInput *)inArg
withOrgApacheLuceneIndexFieldInfo:(OrgApacheLuceneIndexFieldInfo *)fieldInfo
withOrgApacheLuceneCodecsBlockTermState:(OrgApacheLuceneCodecsBlockTermState *)state
                    withBoolean:(jboolean)absolute;

/*!
 @brief Performs any initialization, such as reading and
 verifying the header from the provided terms
 dictionary <code>IndexInput</code>.
 */
- (void)init__WithOrgApacheLuceneStoreIndexInput:(OrgApacheLuceneStoreIndexInput *)termsIn
        withOrgApacheLuceneIndexSegmentReadState:(OrgApacheLuceneIndexSegmentReadState *)state OBJC_METHOD_FAMILY_NONE;

/*!
 @brief Return a newly created empty TermState
 */
- (OrgApacheLuceneCodecsBlockTermState *)newTermState OBJC_METHOD_FAMILY_NONE;

/*!
 @brief Must fully consume state, since after this call that
 TermState may be reused.
 */
- (OrgApacheLuceneIndexPostingsEnum *)postingsWithOrgApacheLuceneIndexFieldInfo:(OrgApacheLuceneIndexFieldInfo *)fieldInfo
                                        withOrgApacheLuceneCodecsBlockTermState:(OrgApacheLuceneCodecsBlockTermState *)state
                                           withOrgApacheLuceneIndexPostingsEnum:(OrgApacheLuceneIndexPostingsEnum *)reuse
                                                                        withInt:(jint)flags;

#pragma mark Protected

/*!
 @brief Sole constructor.
 (For invocation by subclass 
 constructors, typically implicit.) 
 */
- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneCodecsPostingsReaderBase)

FOUNDATION_EXPORT void OrgApacheLuceneCodecsPostingsReaderBase_init(OrgApacheLuceneCodecsPostingsReaderBase *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneCodecsPostingsReaderBase)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneCodecsPostingsReaderBase")
