//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/compound/hyphenation/Hyphen.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneAnalysisCompoundHyphenationHyphen_INCLUDE_ALL")
#if OrgApacheLuceneAnalysisCompoundHyphenationHyphen_RESTRICT
#define OrgApacheLuceneAnalysisCompoundHyphenationHyphen_INCLUDE_ALL 0
#else
#define OrgApacheLuceneAnalysisCompoundHyphenationHyphen_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneAnalysisCompoundHyphenationHyphen_RESTRICT

#if !defined (_OrgApacheLuceneAnalysisCompoundHyphenationHyphen_) && (OrgApacheLuceneAnalysisCompoundHyphenationHyphen_INCLUDE_ALL || OrgApacheLuceneAnalysisCompoundHyphenationHyphen_INCLUDE)
#define _OrgApacheLuceneAnalysisCompoundHyphenationHyphen_

@interface OrgApacheLuceneAnalysisCompoundHyphenationHyphen : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisCompoundHyphenationHyphen)

FOUNDATION_EXPORT void OrgApacheLuceneAnalysisCompoundHyphenationHyphen_init(OrgApacheLuceneAnalysisCompoundHyphenationHyphen *self);

FOUNDATION_EXPORT OrgApacheLuceneAnalysisCompoundHyphenationHyphen *new_OrgApacheLuceneAnalysisCompoundHyphenationHyphen_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneAnalysisCompoundHyphenationHyphen)

#endif

#pragma pop_macro("OrgApacheLuceneAnalysisCompoundHyphenationHyphen_INCLUDE_ALL")
