//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/codecs/lucene50/Lucene50CompoundReader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader")
#ifdef RESTRICT_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader
#define INCLUDE_ALL_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader 0
#else
#define INCLUDE_ALL_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader 1
#endif
#undef RESTRICT_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader

#if !defined (OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_) && (INCLUDE_ALL_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader || defined(INCLUDE_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader))
#define OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_

#define RESTRICT_OrgApacheLuceneStoreDirectory 1
#define INCLUDE_OrgApacheLuceneStoreDirectory 1
#include "org/apache/lucene/store/Directory.h"

@class IOSObjectArray;
@class OrgApacheLuceneIndexSegmentInfo;
@class OrgApacheLuceneStoreIOContext;
@class OrgApacheLuceneStoreIndexInput;
@class OrgApacheLuceneStoreIndexOutput;
@class OrgApacheLuceneStoreLock;
@protocol JavaUtilCollection;

/*!
 @brief Class for accessing a compound stream.
 This class implements a directory, but is limited to only read operations.
 Directory methods that would normally modify data throw an exception.
 */
@interface OrgApacheLuceneCodecsLucene50Lucene50CompoundReader : OrgApacheLuceneStoreDirectory

#pragma mark Public

/*!
 @brief Create a new CompoundFileDirectory.
 */
- (instancetype)initWithOrgApacheLuceneStoreDirectory:(OrgApacheLuceneStoreDirectory *)directory
                  withOrgApacheLuceneIndexSegmentInfo:(OrgApacheLuceneIndexSegmentInfo *)si
                    withOrgApacheLuceneStoreIOContext:(OrgApacheLuceneStoreIOContext *)context;

- (void)close;

- (OrgApacheLuceneStoreIndexOutput *)createOutputWithNSString:(NSString *)name
                            withOrgApacheLuceneStoreIOContext:(OrgApacheLuceneStoreIOContext *)context;

/*!
 @brief Not implemented
 @throws UnsupportedOperationException always: not supported by CFS
 */
- (void)deleteFileWithNSString:(NSString *)name;

/*!
 @brief Returns the length of a file in the directory.
 @throws IOException if the file does not exist
 */
- (jlong)fileLengthWithNSString:(NSString *)name;

/*!
 @brief Returns an array of strings, one for each file in the directory.
 */
- (IOSObjectArray *)listAll;

- (OrgApacheLuceneStoreLock *)obtainLockWithNSString:(NSString *)name;

- (OrgApacheLuceneStoreIndexInput *)openInputWithNSString:(NSString *)name
                        withOrgApacheLuceneStoreIOContext:(OrgApacheLuceneStoreIOContext *)context;

/*!
 @brief Not implemented
 @throws UnsupportedOperationException always: not supported by CFS
 */
- (void)renameFileWithNSString:(NSString *)from
                  withNSString:(NSString *)to;

- (void)syncWithJavaUtilCollection:(id<JavaUtilCollection>)names;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneCodecsLucene50Lucene50CompoundReader)

FOUNDATION_EXPORT void OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_initWithOrgApacheLuceneStoreDirectory_withOrgApacheLuceneIndexSegmentInfo_withOrgApacheLuceneStoreIOContext_(OrgApacheLuceneCodecsLucene50Lucene50CompoundReader *self, OrgApacheLuceneStoreDirectory *directory, OrgApacheLuceneIndexSegmentInfo *si, OrgApacheLuceneStoreIOContext *context);

FOUNDATION_EXPORT OrgApacheLuceneCodecsLucene50Lucene50CompoundReader *new_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_initWithOrgApacheLuceneStoreDirectory_withOrgApacheLuceneIndexSegmentInfo_withOrgApacheLuceneStoreIOContext_(OrgApacheLuceneStoreDirectory *directory, OrgApacheLuceneIndexSegmentInfo *si, OrgApacheLuceneStoreIOContext *context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneCodecsLucene50Lucene50CompoundReader *create_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_initWithOrgApacheLuceneStoreDirectory_withOrgApacheLuceneIndexSegmentInfo_withOrgApacheLuceneStoreIOContext_(OrgApacheLuceneStoreDirectory *directory, OrgApacheLuceneIndexSegmentInfo *si, OrgApacheLuceneStoreIOContext *context);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneCodecsLucene50Lucene50CompoundReader)

#endif

#if !defined (OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry_) && (INCLUDE_ALL_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader || defined(INCLUDE_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry))
#define OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry_

/*!
 @brief Offset/Length for a slice inside of a compound file
 */
@interface OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry : NSObject {
 @public
  jlong offset_;
  jlong length_;
}

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry)

FOUNDATION_EXPORT void OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry_init(OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry *self);

FOUNDATION_EXPORT OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry *new_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry *create_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneCodecsLucene50Lucene50CompoundReader_FileEntry)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneCodecsLucene50Lucene50CompoundReader")
