//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./highlighter/src/java/org/apache/lucene/search/highlight/SimpleFragmenter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneSearchHighlightSimpleFragmenter_INCLUDE_ALL")
#if OrgApacheLuceneSearchHighlightSimpleFragmenter_RESTRICT
#define OrgApacheLuceneSearchHighlightSimpleFragmenter_INCLUDE_ALL 0
#else
#define OrgApacheLuceneSearchHighlightSimpleFragmenter_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneSearchHighlightSimpleFragmenter_RESTRICT

#if !defined (_OrgApacheLuceneSearchHighlightSimpleFragmenter_) && (OrgApacheLuceneSearchHighlightSimpleFragmenter_INCLUDE_ALL || OrgApacheLuceneSearchHighlightSimpleFragmenter_INCLUDE)
#define _OrgApacheLuceneSearchHighlightSimpleFragmenter_

#define OrgApacheLuceneSearchHighlightFragmenter_RESTRICT 1
#define OrgApacheLuceneSearchHighlightFragmenter_INCLUDE 1
#include "org/apache/lucene/search/highlight/Fragmenter.h"

@class OrgApacheLuceneAnalysisTokenStream;

@interface OrgApacheLuceneSearchHighlightSimpleFragmenter : NSObject < OrgApacheLuceneSearchHighlightFragmenter >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)fragmentSize;

- (jint)getFragmentSize;

- (jboolean)isNewFragment;

- (void)setFragmentSizeWithInt:(jint)size;

- (void)startWithNSString:(NSString *)originalText
withOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)stream;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchHighlightSimpleFragmenter)

FOUNDATION_EXPORT void OrgApacheLuceneSearchHighlightSimpleFragmenter_init(OrgApacheLuceneSearchHighlightSimpleFragmenter *self);

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightSimpleFragmenter *new_OrgApacheLuceneSearchHighlightSimpleFragmenter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgApacheLuceneSearchHighlightSimpleFragmenter_initWithInt_(OrgApacheLuceneSearchHighlightSimpleFragmenter *self, jint fragmentSize);

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightSimpleFragmenter *new_OrgApacheLuceneSearchHighlightSimpleFragmenter_initWithInt_(jint fragmentSize) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchHighlightSimpleFragmenter)

#endif

#pragma pop_macro("OrgApacheLuceneSearchHighlightSimpleFragmenter_INCLUDE_ALL")
