//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./queryparser/src/java/org/apache/lucene/queryparser/flexible/standard/processors/FuzzyQueryNodeProcessor.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/queryparser/flexible/standard/processors/FuzzyQueryNodeProcessor.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor

- (instancetype)init {
  OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor = { 2, "FuzzyQueryNodeProcessor", "org.apache.lucene.queryparser.flexible.standard.processors", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor;
}

@end

void OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor_init(OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor *self) {
  NSObject_init(self);
}

OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor *new_OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor_init() {
  OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor *self = [OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor alloc];
  OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneQueryparserFlexibleStandardProcessorsFuzzyQueryNodeProcessor)
