//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/util/MutableBits.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/util/MutableBits.h"

@interface OrgApacheLuceneUtilMutableBits : NSObject

@end

@implementation OrgApacheLuceneUtilMutableBits

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "clearWithInt:", "clear", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneUtilMutableBits = { 2, "MutableBits", "org.apache.lucene.util", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneUtilMutableBits;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheLuceneUtilMutableBits)
