//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/util/SmallFloat.java
//

#include "J2ObjC_source.h"
#include "java/lang/Float.h"
#include "org/apache/lucene/util/SmallFloat.h"

@implementation OrgApacheLuceneUtilSmallFloat

+ (jbyte)floatToByte315WithFloat:(jfloat)f {
  return OrgApacheLuceneUtilSmallFloat_floatToByte315WithFloat_(f);
}

+ (jfloat)byte315ToFloatWithByte:(jbyte)b {
  return OrgApacheLuceneUtilSmallFloat_byte315ToFloatWithByte_(b);
}

- (instancetype)init {
  OrgApacheLuceneUtilSmallFloat_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "floatToByte315WithFloat:", "floatToByte315", "B", 0x9, NULL, NULL },
    { "byte315ToFloatWithByte:", "byte315ToFloat", "F", 0x9, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneUtilSmallFloat = { 2, "SmallFloat", "org.apache.lucene.util", NULL, 0x1, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneUtilSmallFloat;
}

@end

jbyte OrgApacheLuceneUtilSmallFloat_floatToByte315WithFloat_(jfloat f) {
  OrgApacheLuceneUtilSmallFloat_initialize();
  jint bits = JavaLangFloat_floatToRawIntBitsWithFloat_(f);
  jint smallfloat = JreRShift32(bits, (24 - 3));
  if (smallfloat <= (JreLShift32((63 - 15), 3))) {
    return (bits <= 0) ? (jbyte) 0 : (jbyte) 1;
  }
  if (smallfloat >= (JreLShift32((63 - 15), 3)) + (jint) 0x100) {
    return -1;
  }
  return (jbyte) (smallfloat - (JreLShift32((63 - 15), 3)));
}

jfloat OrgApacheLuceneUtilSmallFloat_byte315ToFloatWithByte_(jbyte b) {
  OrgApacheLuceneUtilSmallFloat_initialize();
  if (b == 0) return 0.0f;
  jint bits = JreLShift32((b & (jint) 0xff), (24 - 3));
  bits += JreLShift32((63 - 15), 24);
  return JavaLangFloat_intBitsToFloatWithInt_(bits);
}

void OrgApacheLuceneUtilSmallFloat_init(OrgApacheLuceneUtilSmallFloat *self) {
  NSObject_init(self);
}

OrgApacheLuceneUtilSmallFloat *new_OrgApacheLuceneUtilSmallFloat_init() {
  OrgApacheLuceneUtilSmallFloat *self = [OrgApacheLuceneUtilSmallFloat alloc];
  OrgApacheLuceneUtilSmallFloat_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneUtilSmallFloat)
