//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/util/Accountables.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneUtilAccountables_INCLUDE_ALL")
#if OrgApacheLuceneUtilAccountables_RESTRICT
#define OrgApacheLuceneUtilAccountables_INCLUDE_ALL 0
#else
#define OrgApacheLuceneUtilAccountables_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneUtilAccountables_RESTRICT

#if !defined (_OrgApacheLuceneUtilAccountables_) && (OrgApacheLuceneUtilAccountables_INCLUDE_ALL || OrgApacheLuceneUtilAccountables_INCLUDE)
#define _OrgApacheLuceneUtilAccountables_

@interface OrgApacheLuceneUtilAccountables : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneUtilAccountables)

FOUNDATION_EXPORT void OrgApacheLuceneUtilAccountables_init(OrgApacheLuceneUtilAccountables *self);

FOUNDATION_EXPORT OrgApacheLuceneUtilAccountables *new_OrgApacheLuceneUtilAccountables_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneUtilAccountables)

#endif

#pragma pop_macro("OrgApacheLuceneUtilAccountables_INCLUDE_ALL")
