//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/pt/PortugueseStemFilter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneAnalysisPtPortugueseStemFilter_INCLUDE_ALL")
#if OrgApacheLuceneAnalysisPtPortugueseStemFilter_RESTRICT
#define OrgApacheLuceneAnalysisPtPortugueseStemFilter_INCLUDE_ALL 0
#else
#define OrgApacheLuceneAnalysisPtPortugueseStemFilter_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneAnalysisPtPortugueseStemFilter_RESTRICT

#if !defined (_OrgApacheLuceneAnalysisPtPortugueseStemFilter_) && (OrgApacheLuceneAnalysisPtPortugueseStemFilter_INCLUDE_ALL || OrgApacheLuceneAnalysisPtPortugueseStemFilter_INCLUDE)
#define _OrgApacheLuceneAnalysisPtPortugueseStemFilter_

#define OrgApacheLuceneAnalysisTokenFilter_RESTRICT 1
#define OrgApacheLuceneAnalysisTokenFilter_INCLUDE 1
#include "org/apache/lucene/analysis/TokenFilter.h"

@class OrgApacheLuceneAnalysisTokenStream;

@interface OrgApacheLuceneAnalysisPtPortugueseStemFilter : OrgApacheLuceneAnalysisTokenFilter

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)input;

- (jboolean)incrementToken;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisPtPortugueseStemFilter)

FOUNDATION_EXPORT void OrgApacheLuceneAnalysisPtPortugueseStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisPtPortugueseStemFilter *self, OrgApacheLuceneAnalysisTokenStream *input);

FOUNDATION_EXPORT OrgApacheLuceneAnalysisPtPortugueseStemFilter *new_OrgApacheLuceneAnalysisPtPortugueseStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisTokenStream *input) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneAnalysisPtPortugueseStemFilter)

#endif

#pragma pop_macro("OrgApacheLuceneAnalysisPtPortugueseStemFilter_INCLUDE_ALL")
