//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/tr/TurkishLowerCaseFilter.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/analysis/tr/TurkishLowerCaseFilter.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter

- (instancetype)init {
  OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter = { 2, "TurkishLowerCaseFilter", "org.apache.lucene.analysis.tr", NULL, 0x11, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter;
}

@end

void OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter_init(OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter *self) {
  NSObject_init(self);
}

OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter *new_OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter_init() {
  OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter *self = [OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter alloc];
  OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisTrTurkishLowerCaseFilter)
