//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/hunspell/HunspellStemFilter.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Integer.h"
#include "java/util/Collections.h"
#include "java/util/Comparator.h"
#include "java/util/List.h"
#include "java/util/function/Function.h"
#include "java/util/function/ToDoubleFunction.h"
#include "java/util/function/ToIntFunction.h"
#include "java/util/function/ToLongFunction.h"
#include "org/apache/lucene/analysis/TokenFilter.h"
#include "org/apache/lucene/analysis/TokenStream.h"
#include "org/apache/lucene/analysis/hunspell/Dictionary.h"
#include "org/apache/lucene/analysis/hunspell/HunspellStemFilter.h"
#include "org/apache/lucene/analysis/hunspell/Stemmer.h"
#include "org/apache/lucene/analysis/tokenattributes/CharTermAttribute.h"
#include "org/apache/lucene/analysis/tokenattributes/KeywordAttribute.h"
#include "org/apache/lucene/analysis/tokenattributes/PositionIncrementAttribute.h"
#include "org/apache/lucene/util/AttributeSource.h"
#include "org/apache/lucene/util/CharsRef.h"

#if __has_feature(objc_arc)
#error "org/apache/lucene/analysis/hunspell/HunspellStemFilter must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic ignored "-Wprotocol"

@interface OrgApacheLuceneAnalysisHunspellHunspellStemFilter () {
 @public
  id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute> termAtt_;
  id<OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute> posIncAtt_;
  id<OrgApacheLuceneAnalysisTokenattributesKeywordAttribute> keywordAtt_;
  OrgApacheLuceneAnalysisHunspellStemmer *stemmer_;
  id<JavaUtilList> buffer_;
  OrgApacheLuceneUtilAttributeSource_State *savedState_;
  jboolean dedup_;
  jboolean longestOnly_;
}

@end

J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, termAtt_, id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, posIncAtt_, id<OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, keywordAtt_, id<OrgApacheLuceneAnalysisTokenattributesKeywordAttribute>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, stemmer_, OrgApacheLuceneAnalysisHunspellStemmer *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, buffer_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, savedState_, OrgApacheLuceneUtilAttributeSource_State *)

@interface OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1 : NSObject < JavaUtilComparator >

- (instancetype)init;

- (jint)compareWithId:(OrgApacheLuceneUtilCharsRef *)o1
               withId:(OrgApacheLuceneUtilCharsRef *)o2;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1)

__attribute__((unused)) static void OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1_init(OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1 *self);

__attribute__((unused)) static OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1 *new_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1 *create_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1_init(void);

J2OBJC_INITIALIZED_DEFN(OrgApacheLuceneAnalysisHunspellHunspellStemFilter)

id<JavaUtilComparator> OrgApacheLuceneAnalysisHunspellHunspellStemFilter_lengthComparator;

@implementation OrgApacheLuceneAnalysisHunspellHunspellStemFilter

+ (id<JavaUtilComparator>)lengthComparator {
  return OrgApacheLuceneAnalysisHunspellHunspellStemFilter_lengthComparator;
}

- (instancetype)initWithOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)input
             withOrgApacheLuceneAnalysisHunspellDictionary:(OrgApacheLuceneAnalysisHunspellDictionary *)dictionary {
  OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_(self, input, dictionary);
  return self;
}

- (instancetype)initWithOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)input
             withOrgApacheLuceneAnalysisHunspellDictionary:(OrgApacheLuceneAnalysisHunspellDictionary *)dictionary
                                               withBoolean:(jboolean)dedup {
  OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_(self, input, dictionary, dedup);
  return self;
}

- (instancetype)initWithOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)input
             withOrgApacheLuceneAnalysisHunspellDictionary:(OrgApacheLuceneAnalysisHunspellDictionary *)dictionary
                                               withBoolean:(jboolean)dedup
                                               withBoolean:(jboolean)longestOnly {
  OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_withBoolean_(self, input, dictionary, dedup, longestOnly);
  return self;
}

- (jboolean)incrementToken {
  if (buffer_ != nil && ![buffer_ isEmpty]) {
    OrgApacheLuceneUtilCharsRef *nextStem = JreRetainedLocalValue([buffer_ removeWithInt:0]);
    [self restoreStateWithOrgApacheLuceneUtilAttributeSource_State:savedState_];
    [((id<OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute>) nil_chk(posIncAtt_)) setPositionIncrementWithInt:0];
    [((id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute>) nil_chk([((id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute>) nil_chk(termAtt_)) setEmpty])) appendWithJavaLangCharSequence:nextStem];
    return true;
  }
  if (![((OrgApacheLuceneAnalysisTokenStream *) nil_chk(input_)) incrementToken]) {
    return false;
  }
  if ([((id<OrgApacheLuceneAnalysisTokenattributesKeywordAttribute>) nil_chk(keywordAtt_)) isKeyword]) {
    return true;
  }
  JreStrongAssign(&buffer_, dedup_ ? [((OrgApacheLuceneAnalysisHunspellStemmer *) nil_chk(stemmer_)) uniqueStemsWithCharArray:[((id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute>) nil_chk(termAtt_)) buffer] withInt:[termAtt_ java_length]] : [((OrgApacheLuceneAnalysisHunspellStemmer *) nil_chk(stemmer_)) stemWithCharArray:[((id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute>) nil_chk(termAtt_)) buffer] withInt:[termAtt_ java_length]]);
  if ([buffer_ isEmpty]) {
    return true;
  }
  if (longestOnly_ && [((id<JavaUtilList>) nil_chk(buffer_)) size] > 1) {
    JavaUtilCollections_sortWithJavaUtilList_withJavaUtilComparator_(buffer_, OrgApacheLuceneAnalysisHunspellHunspellStemFilter_lengthComparator);
  }
  OrgApacheLuceneUtilCharsRef *stem = JreRetainedLocalValue([((id<JavaUtilList>) nil_chk(buffer_)) removeWithInt:0]);
  [((id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute>) nil_chk([termAtt_ setEmpty])) appendWithJavaLangCharSequence:stem];
  if (longestOnly_) {
    [((id<JavaUtilList>) nil_chk(buffer_)) clear];
  }
  else {
    if (![((id<JavaUtilList>) nil_chk(buffer_)) isEmpty]) {
      JreStrongAssign(&savedState_, [self captureState]);
    }
  }
  return true;
}

- (void)reset {
  [super reset];
  JreStrongAssign(&buffer_, nil);
}

- (void)dealloc {
  RELEASE_(termAtt_);
  RELEASE_(posIncAtt_);
  RELEASE_(keywordAtt_);
  RELEASE_(stemmer_);
  RELEASE_(buffer_);
  RELEASE_(savedState_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, 3, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 3, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithOrgApacheLuceneAnalysisTokenStream:withOrgApacheLuceneAnalysisHunspellDictionary:);
  methods[1].selector = @selector(initWithOrgApacheLuceneAnalysisTokenStream:withOrgApacheLuceneAnalysisHunspellDictionary:withBoolean:);
  methods[2].selector = @selector(initWithOrgApacheLuceneAnalysisTokenStream:withOrgApacheLuceneAnalysisHunspellDictionary:withBoolean:withBoolean:);
  methods[3].selector = @selector(incrementToken);
  methods[4].selector = @selector(reset);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "termAtt_", "LOrgApacheLuceneAnalysisTokenattributesCharTermAttribute;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "posIncAtt_", "LOrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "keywordAtt_", "LOrgApacheLuceneAnalysisTokenattributesKeywordAttribute;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "stemmer_", "LOrgApacheLuceneAnalysisHunspellStemmer;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "buffer_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 4, -1 },
    { "savedState_", "LOrgApacheLuceneUtilAttributeSource_State;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "dedup_", "Z", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "longestOnly_", "Z", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "lengthComparator", "LJavaUtilComparator;", .constantValue.asLong = 0, 0x18, -1, 5, 6, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneAnalysisTokenStream;LOrgApacheLuceneAnalysisHunspellDictionary;", "LOrgApacheLuceneAnalysisTokenStream;LOrgApacheLuceneAnalysisHunspellDictionary;Z", "LOrgApacheLuceneAnalysisTokenStream;LOrgApacheLuceneAnalysisHunspellDictionary;ZZ", "LJavaIoIOException;", "Ljava/util/List<Lorg/apache/lucene/util/CharsRef;>;", &OrgApacheLuceneAnalysisHunspellHunspellStemFilter_lengthComparator, "Ljava/util/Comparator<Lorg/apache/lucene/util/CharsRef;>;" };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisHunspellHunspellStemFilter = { "HunspellStemFilter", "org.apache.lucene.analysis.hunspell", ptrTable, methods, fields, 7, 0x11, 5, 9, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneAnalysisHunspellHunspellStemFilter;
}

+ (void)initialize {
  if (self == [OrgApacheLuceneAnalysisHunspellHunspellStemFilter class]) {
    JreStrongAssignAndConsume(&OrgApacheLuceneAnalysisHunspellHunspellStemFilter_lengthComparator, new_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1_init());
    J2OBJC_SET_INITIALIZED(OrgApacheLuceneAnalysisHunspellHunspellStemFilter)
  }
}

@end

void OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_(OrgApacheLuceneAnalysisHunspellHunspellStemFilter *self, OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisHunspellDictionary *dictionary) {
  OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_(self, input, dictionary, true);
}

OrgApacheLuceneAnalysisHunspellHunspellStemFilter *new_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_(OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisHunspellDictionary *dictionary) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_, input, dictionary)
}

OrgApacheLuceneAnalysisHunspellHunspellStemFilter *create_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_(OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisHunspellDictionary *dictionary) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_, input, dictionary)
}

void OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_(OrgApacheLuceneAnalysisHunspellHunspellStemFilter *self, OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisHunspellDictionary *dictionary, jboolean dedup) {
  OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_withBoolean_(self, input, dictionary, dedup, false);
}

OrgApacheLuceneAnalysisHunspellHunspellStemFilter *new_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_(OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisHunspellDictionary *dictionary, jboolean dedup) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_, input, dictionary, dedup)
}

OrgApacheLuceneAnalysisHunspellHunspellStemFilter *create_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_(OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisHunspellDictionary *dictionary, jboolean dedup) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_, input, dictionary, dedup)
}

void OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_withBoolean_(OrgApacheLuceneAnalysisHunspellHunspellStemFilter *self, OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisHunspellDictionary *dictionary, jboolean dedup, jboolean longestOnly) {
  OrgApacheLuceneAnalysisTokenFilter_initWithOrgApacheLuceneAnalysisTokenStream_(self, input);
  JreStrongAssign(&self->termAtt_, [self addAttributeWithIOSClass:OrgApacheLuceneAnalysisTokenattributesCharTermAttribute_class_()]);
  JreStrongAssign(&self->posIncAtt_, [self addAttributeWithIOSClass:OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute_class_()]);
  JreStrongAssign(&self->keywordAtt_, [self addAttributeWithIOSClass:OrgApacheLuceneAnalysisTokenattributesKeywordAttribute_class_()]);
  self->dedup_ = (dedup && longestOnly == false);
  JreStrongAssignAndConsume(&self->stemmer_, new_OrgApacheLuceneAnalysisHunspellStemmer_initPackagePrivateWithOrgApacheLuceneAnalysisHunspellDictionary_(dictionary));
  self->longestOnly_ = longestOnly;
}

OrgApacheLuceneAnalysisHunspellHunspellStemFilter *new_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_withBoolean_(OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisHunspellDictionary *dictionary, jboolean dedup, jboolean longestOnly) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_withBoolean_, input, dictionary, dedup, longestOnly)
}

OrgApacheLuceneAnalysisHunspellHunspellStemFilter *create_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_withBoolean_(OrgApacheLuceneAnalysisTokenStream *input, OrgApacheLuceneAnalysisHunspellDictionary *dictionary, jboolean dedup, jboolean longestOnly) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneAnalysisHunspellHunspellStemFilter, initWithOrgApacheLuceneAnalysisTokenStream_withOrgApacheLuceneAnalysisHunspellDictionary_withBoolean_withBoolean_, input, dictionary, dedup, longestOnly)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisHunspellHunspellStemFilter)

@implementation OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jint)compareWithId:(OrgApacheLuceneUtilCharsRef *)o1
               withId:(OrgApacheLuceneUtilCharsRef *)o2 {
  jint cmp = JavaLangInteger_compareWithInt_withInt_(((OrgApacheLuceneUtilCharsRef *) nil_chk(o2))->length_, ((OrgApacheLuceneUtilCharsRef *) nil_chk(o1))->length_);
  if (cmp == 0) {
    return [o2 compareToWithId:o1];
  }
  else {
    return cmp;
  }
}

- (id<JavaUtilComparator>)reversed {
  return JavaUtilComparator_reversed(self);
}

- (id<JavaUtilComparator>)thenComparingWithJavaUtilComparator:(id<JavaUtilComparator>)arg0 {
  return JavaUtilComparator_thenComparingWithJavaUtilComparator_(self, arg0);
}

- (id<JavaUtilComparator>)thenComparingWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0
                                             withJavaUtilComparator:(id<JavaUtilComparator>)arg1 {
  return JavaUtilComparator_thenComparingWithJavaUtilFunctionFunction_withJavaUtilComparator_(self, arg0, arg1);
}

- (id<JavaUtilComparator>)thenComparingWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilComparator_thenComparingWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilComparator>)thenComparingIntWithJavaUtilFunctionToIntFunction:(id<JavaUtilFunctionToIntFunction>)arg0 {
  return JavaUtilComparator_thenComparingIntWithJavaUtilFunctionToIntFunction_(self, arg0);
}

- (id<JavaUtilComparator>)thenComparingLongWithJavaUtilFunctionToLongFunction:(id<JavaUtilFunctionToLongFunction>)arg0 {
  return JavaUtilComparator_thenComparingLongWithJavaUtilFunctionToLongFunction_(self, arg0);
}

- (id<JavaUtilComparator>)thenComparingDoubleWithJavaUtilFunctionToDoubleFunction:(id<JavaUtilFunctionToDoubleFunction>)arg0 {
  return JavaUtilComparator_thenComparingDoubleWithJavaUtilFunctionToDoubleFunction_(self, arg0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(compareWithId:withId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "compare", "LOrgApacheLuceneUtilCharsRef;LOrgApacheLuceneUtilCharsRef;", "LOrgApacheLuceneAnalysisHunspellHunspellStemFilter;", "Ljava/lang/Object;Ljava/util/Comparator<Lorg/apache/lucene/util/CharsRef;>;" };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1 = { "", "org.apache.lucene.analysis.hunspell", ptrTable, methods, NULL, 7, 0x8018, 2, 0, 2, -1, -1, 3, -1 };
  return &_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1;
}

@end

void OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1_init(OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1 *self) {
  NSObject_init(self);
}

OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1 *new_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1_init() {
  J2OBJC_NEW_IMPL(OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1, init)
}

OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1 *create_OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1_init() {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneAnalysisHunspellHunspellStemFilter_1, init)
}
