//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/ngram/Lucene43EdgeNGramTokenizer.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/io/IOException.h"
#include "java/io/Reader.h"
#include "java/lang/Deprecated.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Math.h"
#include "org/apache/lucene/analysis/Tokenizer.h"
#include "org/apache/lucene/analysis/ngram/Lucene43EdgeNGramTokenizer.h"
#include "org/apache/lucene/analysis/tokenattributes/CharTermAttribute.h"
#include "org/apache/lucene/analysis/tokenattributes/OffsetAttribute.h"
#include "org/apache/lucene/analysis/tokenattributes/PositionIncrementAttribute.h"
#include "org/apache/lucene/util/ArrayUtil.h"
#include "org/apache/lucene/util/AttributeFactory.h"
#include "org/apache/lucene/util/AttributeSource.h"

@interface OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer () {
 @public
  id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute> termAtt_;
  id<OrgApacheLuceneAnalysisTokenattributesOffsetAttribute> offsetAtt_;
  id<OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute> posIncrAtt_;
  jint minGram_;
  jint maxGram_;
  jint gramSize_;
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *side_;
  jboolean started_;
  jint inLen_;
  jint charsRead_;
  NSString *inStr_;
}

- (void)init__WithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum:(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *)side
                                                                          withInt:(jint)minGram
                                                                          withInt:(jint)maxGram OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer, termAtt_, id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer, offsetAtt_, id<OrgApacheLuceneAnalysisTokenattributesOffsetAttribute>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer, posIncrAtt_, id<OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer, side_, OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer, inStr_, NSString *)

__attribute__((unused)) static void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_init__WithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self, OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *side, jint minGram, jint maxGram);

__attribute__((unused)) static void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_initWithNSString_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *self, NSString *__name, jint __ordinal);

@interface OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum : OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum < NSCopying >

- (NSString *)getLabel;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum)

__attribute__((unused)) static void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum_initWithNSString_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum)

@interface OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum : OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum < NSCopying >

- (NSString *)getLabel;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum)

__attribute__((unused)) static void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum_initWithNSString_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum)

J2OBJC_INITIALIZED_DEFN(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer)

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_DEFAULT_SIDE_;

@implementation OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer

- (instancetype)initWithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum:(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *)side
                                                                                withInt:(jint)minGram
                                                                                withInt:(jint)maxGram {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, side, minGram, maxGram);
  return self;
}

- (instancetype)initWithOrgApacheLuceneUtilAttributeFactory:(OrgApacheLuceneUtilAttributeFactory *)factory
withOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum:(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *)side
                                                    withInt:(jint)minGram
                                                    withInt:(jint)maxGram {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, factory, side, minGram, maxGram);
  return self;
}

- (instancetype)initWithOrgApacheLuceneUtilAttributeFactory:(OrgApacheLuceneUtilAttributeFactory *)factory
                                               withNSString:(NSString *)sideLabel
                                                    withInt:(jint)minGram
                                                    withInt:(jint)maxGram {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withNSString_withInt_withInt_(self, factory, sideLabel, minGram, maxGram);
  return self;
}

- (instancetype)initWithInt:(jint)minGram
                    withInt:(jint)maxGram {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithInt_withInt_(self, minGram, maxGram);
  return self;
}

- (instancetype)initWithNSString:(NSString *)sideLabel
                         withInt:(jint)minGram
                         withInt:(jint)maxGram {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithNSString_withInt_withInt_(self, sideLabel, minGram, maxGram);
  return self;
}

- (instancetype)initWithOrgApacheLuceneUtilAttributeFactory:(OrgApacheLuceneUtilAttributeFactory *)factory
                                                    withInt:(jint)minGram
                                                    withInt:(jint)maxGram {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withInt_withInt_(self, factory, minGram, maxGram);
  return self;
}

- (void)init__WithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum:(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *)side
                                                                          withInt:(jint)minGram
                                                                          withInt:(jint)maxGram {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_init__WithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, side, minGram, maxGram);
}

- (jboolean)incrementToken {
  [self clearAttributes];
  if (!started_) {
    started_ = YES;
    gramSize_ = minGram_;
    jint limit = side_ == JreLoadStatic(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum, FRONT) ? maxGram_ : 1024;
    IOSCharArray *chars = [IOSCharArray arrayWithLength:JavaLangMath_minWithInt_withInt_(1024, limit)];
    charsRead_ = 0;
    jboolean exhausted = NO;
    while (charsRead_ < limit) {
      jint inc = [((JavaIoReader *) nil_chk(input_)) readWithCharArray:chars withInt:charsRead_ withInt:chars->size_ - charsRead_];
      if (inc == -1) {
        exhausted = YES;
        break;
      }
      charsRead_ += inc;
      if (charsRead_ == chars->size_ && charsRead_ < limit) {
        chars = OrgApacheLuceneUtilArrayUtil_growWithCharArray_(chars);
      }
    }
    JreStrongAssign(&inStr_, [NSString stringWithCharacters:chars offset:0 length:charsRead_]);
    JreStrongAssign(&inStr_, [inStr_ trim]);
    if (!exhausted) {
      IOSCharArray *throwaway = [IOSCharArray arrayWithLength:1024];
      while (YES) {
        jint inc = [((JavaIoReader *) nil_chk(input_)) readWithCharArray:throwaway withInt:0 withInt:throwaway->size_];
        if (inc == -1) {
          break;
        }
        charsRead_ += inc;
      }
    }
    inLen_ = ((jint) [((NSString *) nil_chk(inStr_)) length]);
    if (inLen_ == 0) {
      return NO;
    }
    [((id<OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute>) nil_chk(posIncrAtt_)) setPositionIncrementWithInt:1];
  }
  else {
    [((id<OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute>) nil_chk(posIncrAtt_)) setPositionIncrementWithInt:0];
  }
  if (gramSize_ > inLen_) {
    return NO;
  }
  if (gramSize_ > maxGram_ || gramSize_ > inLen_) {
    return NO;
  }
  jint start = side_ == JreLoadStatic(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum, FRONT) ? 0 : inLen_ - gramSize_;
  jint end = start + gramSize_;
  [((id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute>) nil_chk([((id<OrgApacheLuceneAnalysisTokenattributesCharTermAttribute>) nil_chk(termAtt_)) setEmpty])) appendWithJavaLangCharSequence:inStr_ withInt:start withInt:end];
  [((id<OrgApacheLuceneAnalysisTokenattributesOffsetAttribute>) nil_chk(offsetAtt_)) setOffsetWithInt:[self correctOffsetWithInt:start] withInt:[self correctOffsetWithInt:end]];
  gramSize_++;
  return YES;
}

- (void)end {
  [super end];
  jint finalOffset = [self correctOffsetWithInt:charsRead_];
  [((id<OrgApacheLuceneAnalysisTokenattributesOffsetAttribute>) nil_chk(self->offsetAtt_)) setOffsetWithInt:finalOffset withInt:finalOffset];
}

- (void)reset {
  [super reset];
  started_ = NO;
}

- (void)dealloc {
  RELEASE_(termAtt_);
  RELEASE_(offsetAtt_);
  RELEASE_(posIncrAtt_);
  RELEASE_(side_);
  RELEASE_(inStr_);
  [super dealloc];
}

+ (void)initialize {
  if (self == [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer class]) {
    JreStrongAssign(&OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_DEFAULT_SIDE_, JreLoadStatic(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum, FRONT));
    J2OBJC_SET_INITIALIZED(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer)
  }
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangDeprecated alloc] init] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_initWithNSString_withInt_withInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangDeprecated alloc] init] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum:withInt:withInt:", "Lucene43EdgeNGramTokenizer", NULL, 0x1, NULL, NULL },
    { "initWithOrgApacheLuceneUtilAttributeFactory:withOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum:withInt:withInt:", "Lucene43EdgeNGramTokenizer", NULL, 0x1, NULL, NULL },
    { "initWithOrgApacheLuceneUtilAttributeFactory:withNSString:withInt:withInt:", "Lucene43EdgeNGramTokenizer", NULL, 0x1, NULL, NULL },
    { "initWithInt:withInt:", "Lucene43EdgeNGramTokenizer", NULL, 0x1, NULL, NULL },
    { "initWithNSString:withInt:withInt:", "Lucene43EdgeNGramTokenizer", NULL, 0x1, NULL, NULL },
    { "initWithOrgApacheLuceneUtilAttributeFactory:withInt:withInt:", "Lucene43EdgeNGramTokenizer", NULL, 0x1, NULL, NULL },
    { "init__WithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum:withInt:withInt:", "init", "V", 0x2, NULL, NULL },
    { "incrementToken", NULL, "Z", 0x1, "Ljava.io.IOException;", NULL },
    { "end", NULL, "V", 0x1, "Ljava.io.IOException;", NULL },
    { "reset", NULL, "V", 0x1, "Ljava.io.IOException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "DEFAULT_SIDE_", NULL, 0x19, "Lorg.apache.lucene.analysis.ngram.Lucene43EdgeNGramTokenizer$Side;", &OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_DEFAULT_SIDE_, NULL, .constantValue.asLong = 0 },
    { "DEFAULT_MAX_GRAM_SIZE", "DEFAULT_MAX_GRAM_SIZE", 0x19, "I", NULL, NULL, .constantValue.asInt = OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_DEFAULT_MAX_GRAM_SIZE },
    { "DEFAULT_MIN_GRAM_SIZE", "DEFAULT_MIN_GRAM_SIZE", 0x19, "I", NULL, NULL, .constantValue.asInt = OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_DEFAULT_MIN_GRAM_SIZE },
    { "termAtt_", NULL, 0x12, "Lorg.apache.lucene.analysis.tokenattributes.CharTermAttribute;", NULL, NULL, .constantValue.asLong = 0 },
    { "offsetAtt_", NULL, 0x12, "Lorg.apache.lucene.analysis.tokenattributes.OffsetAttribute;", NULL, NULL, .constantValue.asLong = 0 },
    { "posIncrAtt_", NULL, 0x12, "Lorg.apache.lucene.analysis.tokenattributes.PositionIncrementAttribute;", NULL, NULL, .constantValue.asLong = 0 },
    { "minGram_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "maxGram_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "gramSize_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "side_", NULL, 0x2, "Lorg.apache.lucene.analysis.ngram.Lucene43EdgeNGramTokenizer$Side;", NULL, NULL, .constantValue.asLong = 0 },
    { "started_", NULL, 0x2, "Z", NULL, NULL, .constantValue.asLong = 0 },
    { "inLen_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "charsRead_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "inStr_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *inner_classes[] = {"Lorg.apache.lucene.analysis.ngram.Lucene43EdgeNGramTokenizer$Side;"};
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer = { 2, "Lucene43EdgeNGramTokenizer", "org.apache.lucene.analysis.ngram", NULL, 0x11, 10, methods, 14, fields, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer;
}

@end

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self, OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *side, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisTokenizer_init(self);
  JreStrongAssign(&self->termAtt_, [self addAttributeWithIOSClass:OrgApacheLuceneAnalysisTokenattributesCharTermAttribute_class_()]);
  JreStrongAssign(&self->offsetAtt_, [self addAttributeWithIOSClass:OrgApacheLuceneAnalysisTokenattributesOffsetAttribute_class_()]);
  JreStrongAssign(&self->posIncrAtt_, [self addAttributeWithIOSClass:OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute_class_()]);
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_init__WithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, side, minGram, maxGram);
}

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *side, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self = [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer alloc];
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, side, minGram, maxGram);
  return self;
}

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self, OrgApacheLuceneUtilAttributeFactory *factory, OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *side, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_(self, factory);
  JreStrongAssign(&self->termAtt_, [self addAttributeWithIOSClass:OrgApacheLuceneAnalysisTokenattributesCharTermAttribute_class_()]);
  JreStrongAssign(&self->offsetAtt_, [self addAttributeWithIOSClass:OrgApacheLuceneAnalysisTokenattributesOffsetAttribute_class_()]);
  JreStrongAssign(&self->posIncrAtt_, [self addAttributeWithIOSClass:OrgApacheLuceneAnalysisTokenattributesPositionIncrementAttribute_class_()]);
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_init__WithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, side, minGram, maxGram);
}

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(OrgApacheLuceneUtilAttributeFactory *factory, OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *side, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self = [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer alloc];
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, factory, side, minGram, maxGram);
  return self;
}

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withNSString_withInt_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self, OrgApacheLuceneUtilAttributeFactory *factory, NSString *sideLabel, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, factory, OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_getSideWithNSString_(sideLabel), minGram, maxGram);
}

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withNSString_withInt_withInt_(OrgApacheLuceneUtilAttributeFactory *factory, NSString *sideLabel, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self = [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer alloc];
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withNSString_withInt_withInt_(self, factory, sideLabel, minGram, maxGram);
  return self;
}

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithInt_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, JreLoadStatic(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum, FRONT), minGram, maxGram);
}

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithInt_withInt_(jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self = [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer alloc];
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithInt_withInt_(self, minGram, maxGram);
  return self;
}

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithNSString_withInt_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self, NSString *sideLabel, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_getSideWithNSString_(sideLabel), minGram, maxGram);
}

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithNSString_withInt_withInt_(NSString *sideLabel, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self = [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer alloc];
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithNSString_withInt_withInt_(self, sideLabel, minGram, maxGram);
  return self;
}

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withInt_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self, OrgApacheLuceneUtilAttributeFactory *factory, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(self, factory, JreLoadStatic(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum, FRONT), minGram, maxGram);
}

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withInt_withInt_(OrgApacheLuceneUtilAttributeFactory *factory, jint minGram, jint maxGram) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self = [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer alloc];
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_initWithOrgApacheLuceneUtilAttributeFactory_withInt_withInt_(self, factory, minGram, maxGram);
  return self;
}

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_init__WithOrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_withInt_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer *self, OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *side, jint minGram, jint maxGram) {
  if (side == nil) {
    @throw [new_JavaLangIllegalArgumentException_initWithNSString_(@"sideLabel must be either front or back") autorelease];
  }
  if (minGram < 1) {
    @throw [new_JavaLangIllegalArgumentException_initWithNSString_(@"minGram must be greater than zero") autorelease];
  }
  if (minGram > maxGram) {
    @throw [new_JavaLangIllegalArgumentException_initWithNSString_(@"minGram must not be greater than maxGram") autorelease];
  }
  maxGram = JavaLangMath_minWithInt_withInt_(maxGram, 1024);
  self->minGram_ = minGram;
  self->maxGram_ = maxGram;
  JreStrongAssign(&self->side_, side);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer)

J2OBJC_INITIALIZED_DEFN(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum)

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_values_[2];

@implementation OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum

- (NSString *)getLabel {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

+ (OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *)getSideWithNSString:(NSString *)sideName {
  return OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_getSideWithNSString_(sideName);
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_values() {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_initialize();
  return [IOSObjectArray arrayWithObjects:OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_values_ count:2 type:OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_class_()];
}

+ (IOSObjectArray *)values {
  return OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_values();
}

+ (OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *)valueOfWithNSString:(NSString *)name {
  return OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_valueOfWithNSString_(name);
}

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_valueOfWithNSString_(NSString *name) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_initialize();
  for (int i = 0; i < 2; i++) {
    OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *e = OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum class]) {
    OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_FRONT = new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum_initWithNSString_withInt_(@"FRONT", 0);
    OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_BACK = new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum_initWithNSString_withInt_(@"BACK", 1);
    J2OBJC_SET_INITIALIZED(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getLabel", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getSideWithNSString:", "getSide", "Lorg.apache.lucene.analysis.ngram.Lucene43EdgeNGramTokenizer$Side;", 0x9, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "FRONT", "FRONT", 0x4019, "Lorg.apache.lucene.analysis.ngram.Lucene43EdgeNGramTokenizer$Side;", &OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_FRONT, NULL, .constantValue.asLong = 0 },
    { "BACK", "BACK", 0x4019, "Lorg.apache.lucene.analysis.ngram.Lucene43EdgeNGramTokenizer$Side;", &OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_BACK, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lorg.apache.lucene.analysis.ngram.Lucene43EdgeNGramTokenizer$Side;"};
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum = { 2, "Side", "org.apache.lucene.analysis.ngram", "Lucene43EdgeNGramTokenizer", 0x4409, 2, methods, 2, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lorg/apache/lucene/analysis/ngram/Lucene43EdgeNGramTokenizer$Side;>;" };
  return &_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum;
}

@end

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_getSideWithNSString_(NSString *sideName) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_initialize();
  if ([((NSString *) nil_chk([((OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *) nil_chk(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_FRONT)) getLabel])) isEqual:sideName]) {
    return OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_FRONT;
  }
  if ([((NSString *) nil_chk([((OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *) nil_chk(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_BACK)) getLabel])) isEqual:sideName]) {
    return OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_BACK;
  }
  return nil;
}

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_initWithNSString_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum)

@implementation OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum

- (NSString *)getLabel {
  return @"front";
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getLabel", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum = { 2, "", "org.apache.lucene.analysis.ngram", "Lucene43EdgeNGramTokenizer$Side", 0xc018, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum;
}

@end

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum_initWithNSString_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum *self, NSString *__name, jint __ordinal) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum *self = [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum alloc];
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$1Enum)

@implementation OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum

- (NSString *)getLabel {
  return @"back";
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getLabel", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum = { 2, "", "org.apache.lucene.analysis.ngram", "Lucene43EdgeNGramTokenizer$Side", 0xc018, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum;
}

@end

void OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum_initWithNSString_withInt_(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum *self, NSString *__name, jint __ordinal) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_SideEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum *new_OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum *self = [OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum alloc];
  OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisNgramLucene43EdgeNGramTokenizer_Side_$2Enum)
