//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/util/fst/IntsRefFSTEnum.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/util/fst/IntsRefFSTEnum.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation OrgApacheLuceneUtilFstIntsRefFSTEnum

- (instancetype)init {
  OrgApacheLuceneUtilFstIntsRefFSTEnum_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"TT;"};
  static const char *inner_classes[] = {"Lorg.apache.lucene.util.fst.IntsRefFSTEnum$InputOutput;"};
  static const J2ObjcClassInfo _OrgApacheLuceneUtilFstIntsRefFSTEnum = { 2, "IntsRefFSTEnum", "org.apache.lucene.util.fst", NULL, 0x11, 1, methods, 0, NULL, 1, superclass_type_args, 1, inner_classes, NULL, "<T:Ljava/lang/Object;>Lorg/apache/lucene/util/fst/FSTEnum<TT;>;" };
  return &_OrgApacheLuceneUtilFstIntsRefFSTEnum;
}

@end

void OrgApacheLuceneUtilFstIntsRefFSTEnum_init(OrgApacheLuceneUtilFstIntsRefFSTEnum *self) {
  NSObject_init(self);
}

OrgApacheLuceneUtilFstIntsRefFSTEnum *new_OrgApacheLuceneUtilFstIntsRefFSTEnum_init() {
  OrgApacheLuceneUtilFstIntsRefFSTEnum *self = [OrgApacheLuceneUtilFstIntsRefFSTEnum alloc];
  OrgApacheLuceneUtilFstIntsRefFSTEnum_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneUtilFstIntsRefFSTEnum)

@implementation OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput

- (instancetype)init {
  OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput = { 2, "InputOutput", "org.apache.lucene.util.fst", "IntsRefFSTEnum", 0x9, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput;
}

@end

void OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput_init(OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput *self) {
  NSObject_init(self);
}

OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput *new_OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput_init() {
  OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput *self = [OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput alloc];
  OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneUtilFstIntsRefFSTEnum_InputOutput)
