//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./queryparser/src/java/org/apache/lucene/queryparser/flexible/core/QueryParserHelper.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/queryparser/flexible/core/QueryParserHelper.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper

- (instancetype)init {
  OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper = { 2, "QueryParserHelper", "org.apache.lucene.queryparser.flexible.core", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper;
}

@end

void OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper_init(OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper *self) {
  NSObject_init(self);
}

OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper *new_OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper_init() {
  OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper *self = [OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper alloc];
  OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneQueryparserFlexibleCoreQueryParserHelper)
