//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./sandbox/src/java/org/apache/lucene/rangetree/RangeTreeSortedNumericDocValues.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/index/SortedNumericDocValues.h"
#include "org/apache/lucene/rangetree/RangeTreeReader.h"
#include "org/apache/lucene/rangetree/RangeTreeSortedNumericDocValues.h"

@implementation OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues

- (instancetype)initWithOrgApacheLuceneRangetreeRangeTreeReader:(OrgApacheLuceneRangetreeRangeTreeReader *)rangeTreeReader
                 withOrgApacheLuceneIndexSortedNumericDocValues:(OrgApacheLuceneIndexSortedNumericDocValues *)delegate {
  OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues_initWithOrgApacheLuceneRangetreeRangeTreeReader_withOrgApacheLuceneIndexSortedNumericDocValues_(self, rangeTreeReader, delegate);
  return self;
}

- (OrgApacheLuceneRangetreeRangeTreeReader *)getRangeTreeReader {
  return rangeTreeReader_;
}

- (void)setDocumentWithInt:(jint)doc {
  [((OrgApacheLuceneIndexSortedNumericDocValues *) nil_chk(delegate_)) setDocumentWithInt:doc];
}

- (jlong)valueAtWithInt:(jint)index {
  return [((OrgApacheLuceneIndexSortedNumericDocValues *) nil_chk(delegate_)) valueAtWithInt:index];
}

- (jint)count {
  return [((OrgApacheLuceneIndexSortedNumericDocValues *) nil_chk(delegate_)) count];
}

- (void)dealloc {
  RELEASE_(rangeTreeReader_);
  RELEASE_(delegate_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgApacheLuceneRangetreeRangeTreeReader:withOrgApacheLuceneIndexSortedNumericDocValues:", "RangeTreeSortedNumericDocValues", NULL, 0x1, NULL, NULL },
    { "getRangeTreeReader", NULL, "Lorg.apache.lucene.rangetree.RangeTreeReader;", 0x1, NULL, NULL },
    { "setDocumentWithInt:", "setDocument", "V", 0x1, NULL, NULL },
    { "valueAtWithInt:", "valueAt", "J", 0x1, NULL, NULL },
    { "count", NULL, "I", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "rangeTreeReader_", NULL, 0x10, "Lorg.apache.lucene.rangetree.RangeTreeReader;", NULL, NULL, .constantValue.asLong = 0 },
    { "delegate_", NULL, 0x10, "Lorg.apache.lucene.index.SortedNumericDocValues;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues = { 2, "RangeTreeSortedNumericDocValues", "org.apache.lucene.rangetree", NULL, 0x0, 5, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues;
}

@end

void OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues_initWithOrgApacheLuceneRangetreeRangeTreeReader_withOrgApacheLuceneIndexSortedNumericDocValues_(OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues *self, OrgApacheLuceneRangetreeRangeTreeReader *rangeTreeReader, OrgApacheLuceneIndexSortedNumericDocValues *delegate) {
  OrgApacheLuceneIndexSortedNumericDocValues_init(self);
  JreStrongAssign(&self->rangeTreeReader_, rangeTreeReader);
  JreStrongAssign(&self->delegate_, delegate);
}

OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues *new_OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues_initWithOrgApacheLuceneRangetreeRangeTreeReader_withOrgApacheLuceneIndexSortedNumericDocValues_(OrgApacheLuceneRangetreeRangeTreeReader *rangeTreeReader, OrgApacheLuceneIndexSortedNumericDocValues *delegate) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues, initWithOrgApacheLuceneRangetreeRangeTreeReader_withOrgApacheLuceneIndexSortedNumericDocValues_, rangeTreeReader, delegate)
}

OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues *create_OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues_initWithOrgApacheLuceneRangetreeRangeTreeReader_withOrgApacheLuceneIndexSortedNumericDocValues_(OrgApacheLuceneRangetreeRangeTreeReader *rangeTreeReader, OrgApacheLuceneIndexSortedNumericDocValues *delegate) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues, initWithOrgApacheLuceneRangetreeRangeTreeReader_withOrgApacheLuceneIndexSortedNumericDocValues_, rangeTreeReader, delegate)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneRangetreeRangeTreeSortedNumericDocValues)
