//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/miscellaneous/LimitTokenCountAnalyzer.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/analysis/miscellaneous/LimitTokenCountAnalyzer.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer

- (instancetype)init {
  OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer = { 2, "LimitTokenCountAnalyzer", "org.apache.lucene.analysis.miscellaneous", NULL, 0x11, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer;
}

@end

void OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer_init(OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer *self) {
  NSObject_init(self);
}

OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer *new_OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer_init() {
  OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer *self = [OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer alloc];
  OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisMiscellaneousLimitTokenCountAnalyzer)
