//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/search/similarities/DistributionSPL.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchSimilaritiesDistributionSPL")
#ifdef RESTRICT_OrgApacheLuceneSearchSimilaritiesDistributionSPL
#define INCLUDE_ALL_OrgApacheLuceneSearchSimilaritiesDistributionSPL 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchSimilaritiesDistributionSPL 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchSimilaritiesDistributionSPL

#if !defined (OrgApacheLuceneSearchSimilaritiesDistributionSPL_) && (INCLUDE_ALL_OrgApacheLuceneSearchSimilaritiesDistributionSPL || defined(INCLUDE_OrgApacheLuceneSearchSimilaritiesDistributionSPL))
#define OrgApacheLuceneSearchSimilaritiesDistributionSPL_

#define RESTRICT_OrgApacheLuceneSearchSimilaritiesDistribution 1
#define INCLUDE_OrgApacheLuceneSearchSimilaritiesDistribution 1
#include "org/apache/lucene/search/similarities/Distribution.h"

@class OrgApacheLuceneSearchSimilaritiesBasicStats;

/*!
 @brief The smoothed power-law (SPL) distribution for the information-based framework
 that is described in the original paper.
 <p>Unlike for DFR, the natural logarithm is used, as
 it is faster to compute and the original paper does not express any
 preference to a specific base.</p>
 */
@interface OrgApacheLuceneSearchSimilaritiesDistributionSPL : OrgApacheLuceneSearchSimilaritiesDistribution

#pragma mark Public

/*!
 @brief Sole constructor: parameter-free
 */
- (instancetype)init;

- (jfloat)scoreWithOrgApacheLuceneSearchSimilaritiesBasicStats:(OrgApacheLuceneSearchSimilaritiesBasicStats *)stats
                                                     withFloat:(jfloat)tfn
                                                     withFloat:(jfloat)lambda;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchSimilaritiesDistributionSPL)

FOUNDATION_EXPORT void OrgApacheLuceneSearchSimilaritiesDistributionSPL_init(OrgApacheLuceneSearchSimilaritiesDistributionSPL *self);

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilaritiesDistributionSPL *new_OrgApacheLuceneSearchSimilaritiesDistributionSPL_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilaritiesDistributionSPL *create_OrgApacheLuceneSearchSimilaritiesDistributionSPL_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchSimilaritiesDistributionSPL)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchSimilaritiesDistributionSPL")
