//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/search/similarities/SimilarityBase.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneSearchSimilaritiesSimilarityBase_INCLUDE_ALL")
#if OrgApacheLuceneSearchSimilaritiesSimilarityBase_RESTRICT
#define OrgApacheLuceneSearchSimilaritiesSimilarityBase_INCLUDE_ALL 0
#else
#define OrgApacheLuceneSearchSimilaritiesSimilarityBase_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneSearchSimilaritiesSimilarityBase_RESTRICT

#if !defined (_OrgApacheLuceneSearchSimilaritiesSimilarityBase_) && (OrgApacheLuceneSearchSimilaritiesSimilarityBase_INCLUDE_ALL || OrgApacheLuceneSearchSimilaritiesSimilarityBase_INCLUDE)
#define _OrgApacheLuceneSearchSimilaritiesSimilarityBase_

#define OrgApacheLuceneSearchSimilaritiesSimilarity_RESTRICT 1
#define OrgApacheLuceneSearchSimilaritiesSimilarity_INCLUDE 1
#include "org/apache/lucene/search/similarities/Similarity.h"

@interface OrgApacheLuceneSearchSimilaritiesSimilarityBase : OrgApacheLuceneSearchSimilaritiesSimilarity

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchSimilaritiesSimilarityBase)

FOUNDATION_EXPORT void OrgApacheLuceneSearchSimilaritiesSimilarityBase_init(OrgApacheLuceneSearchSimilaritiesSimilarityBase *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchSimilaritiesSimilarityBase)

#endif

#pragma pop_macro("OrgApacheLuceneSearchSimilaritiesSimilarityBase_INCLUDE_ALL")
