//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/lv/LatvianStemFilter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneAnalysisLvLatvianStemFilter")
#ifdef RESTRICT_OrgApacheLuceneAnalysisLvLatvianStemFilter
#define INCLUDE_ALL_OrgApacheLuceneAnalysisLvLatvianStemFilter 0
#else
#define INCLUDE_ALL_OrgApacheLuceneAnalysisLvLatvianStemFilter 1
#endif
#undef RESTRICT_OrgApacheLuceneAnalysisLvLatvianStemFilter

#if !defined (OrgApacheLuceneAnalysisLvLatvianStemFilter_) && (INCLUDE_ALL_OrgApacheLuceneAnalysisLvLatvianStemFilter || defined(INCLUDE_OrgApacheLuceneAnalysisLvLatvianStemFilter))
#define OrgApacheLuceneAnalysisLvLatvianStemFilter_

#define RESTRICT_OrgApacheLuceneAnalysisTokenFilter 1
#define INCLUDE_OrgApacheLuceneAnalysisTokenFilter 1
#include "org/apache/lucene/analysis/TokenFilter.h"

@class OrgApacheLuceneAnalysisTokenStream;

/*!
 @brief A <code>TokenFilter</code> that applies <code>LatvianStemmer</code> to stem Latvian
 words.
 <p>
 To prevent terms from being stemmed use an instance of
 <code>SetKeywordMarkerFilter</code> or a custom <code>TokenFilter</code> that sets
 the <code>KeywordAttribute</code> before this <code>TokenStream</code>.
 </p>
 */
@interface OrgApacheLuceneAnalysisLvLatvianStemFilter : OrgApacheLuceneAnalysisTokenFilter

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)input;

- (jboolean)incrementToken;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisLvLatvianStemFilter)

FOUNDATION_EXPORT void OrgApacheLuceneAnalysisLvLatvianStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisLvLatvianStemFilter *self, OrgApacheLuceneAnalysisTokenStream *input);

FOUNDATION_EXPORT OrgApacheLuceneAnalysisLvLatvianStemFilter *new_OrgApacheLuceneAnalysisLvLatvianStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisTokenStream *input) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneAnalysisLvLatvianStemFilter *create_OrgApacheLuceneAnalysisLvLatvianStemFilter_initWithOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisTokenStream *input);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneAnalysisLvLatvianStemFilter)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneAnalysisLvLatvianStemFilter")
