//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./grouping/src/java/org/apache/lucene/search/grouping/term/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneSearchGroupingTermPackage_info_INCLUDE_ALL")
#if OrgApacheLuceneSearchGroupingTermPackage_info_RESTRICT
#define OrgApacheLuceneSearchGroupingTermPackage_info_INCLUDE_ALL 0
#else
#define OrgApacheLuceneSearchGroupingTermPackage_info_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneSearchGroupingTermPackage_info_RESTRICT

#pragma pop_macro("OrgApacheLuceneSearchGroupingTermPackage_info_INCLUDE_ALL")
