//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/cz/CzechAnalyzer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneAnalysisCzCzechAnalyzer_INCLUDE_ALL")
#if OrgApacheLuceneAnalysisCzCzechAnalyzer_RESTRICT
#define OrgApacheLuceneAnalysisCzCzechAnalyzer_INCLUDE_ALL 0
#else
#define OrgApacheLuceneAnalysisCzCzechAnalyzer_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneAnalysisCzCzechAnalyzer_RESTRICT

#if !defined (_OrgApacheLuceneAnalysisCzCzechAnalyzer_) && (OrgApacheLuceneAnalysisCzCzechAnalyzer_INCLUDE_ALL || OrgApacheLuceneAnalysisCzCzechAnalyzer_INCLUDE)
#define _OrgApacheLuceneAnalysisCzCzechAnalyzer_

#define OrgApacheLuceneAnalysisUtilStopwordAnalyzerBase_RESTRICT 1
#define OrgApacheLuceneAnalysisUtilStopwordAnalyzerBase_INCLUDE 1
#include "org/apache/lucene/analysis/util/StopwordAnalyzerBase.h"

@interface OrgApacheLuceneAnalysisCzCzechAnalyzer : OrgApacheLuceneAnalysisUtilStopwordAnalyzerBase

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisCzCzechAnalyzer)

FOUNDATION_EXPORT NSString *OrgApacheLuceneAnalysisCzCzechAnalyzer_DEFAULT_STOPWORD_FILE_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheLuceneAnalysisCzCzechAnalyzer, DEFAULT_STOPWORD_FILE_, NSString *)

FOUNDATION_EXPORT void OrgApacheLuceneAnalysisCzCzechAnalyzer_init(OrgApacheLuceneAnalysisCzCzechAnalyzer *self);

FOUNDATION_EXPORT OrgApacheLuceneAnalysisCzCzechAnalyzer *new_OrgApacheLuceneAnalysisCzCzechAnalyzer_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneAnalysisCzCzechAnalyzer)

#endif

#pragma pop_macro("OrgApacheLuceneAnalysisCzCzechAnalyzer_INCLUDE_ALL")
