//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./sandbox/src/java/org/apache/lucene/search/GeoPointTermsEnum.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/search/GeoPointTermsEnum.h"
#include "org/apache/lucene/util/GeoUtils.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation OrgApacheLuceneSearchGeoPointTermsEnum

- (instancetype)init {
  OrgApacheLuceneSearchGeoPointTermsEnum_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "DETAIL_LEVEL", "DETAIL_LEVEL", 0x1c, "S", NULL, NULL, .constantValue.asShort = OrgApacheLuceneSearchGeoPointTermsEnum_DETAIL_LEVEL },
  };
  static const char *inner_classes[] = {"Lorg.apache.lucene.search.GeoPointTermsEnum$Range;"};
  static const J2ObjcClassInfo _OrgApacheLuceneSearchGeoPointTermsEnum = { 2, "GeoPointTermsEnum", "org.apache.lucene.search", NULL, 0x400, 1, methods, 1, fields, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_OrgApacheLuceneSearchGeoPointTermsEnum;
}

@end

void OrgApacheLuceneSearchGeoPointTermsEnum_init(OrgApacheLuceneSearchGeoPointTermsEnum *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchGeoPointTermsEnum)
