//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/search/RegexpQuery.java
//

#include "J2ObjC_source.h"
#include "java/lang/StringBuilder.h"
#include "org/apache/lucene/index/Term.h"
#include "org/apache/lucene/search/AutomatonQuery.h"
#include "org/apache/lucene/search/Query.h"
#include "org/apache/lucene/search/RegexpQuery.h"
#include "org/apache/lucene/util/ToStringUtils.h"
#include "org/apache/lucene/util/automaton/Automaton.h"
#include "org/apache/lucene/util/automaton/AutomatonProvider.h"
#include "org/apache/lucene/util/automaton/Operations.h"
#include "org/apache/lucene/util/automaton/RegExp.h"

static id<OrgApacheLuceneUtilAutomatonAutomatonProvider> OrgApacheLuceneSearchRegexpQuery_defaultProvider_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheLuceneSearchRegexpQuery, defaultProvider_, id<OrgApacheLuceneUtilAutomatonAutomatonProvider>)
J2OBJC_STATIC_FIELD_SETTER(OrgApacheLuceneSearchRegexpQuery, defaultProvider_, id<OrgApacheLuceneUtilAutomatonAutomatonProvider>)

@interface OrgApacheLuceneSearchRegexpQuery_$1 : NSObject < OrgApacheLuceneUtilAutomatonAutomatonProvider >

- (OrgApacheLuceneUtilAutomatonAutomaton *)getAutomatonWithNSString:(NSString *)name;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchRegexpQuery_$1)

__attribute__((unused)) static void OrgApacheLuceneSearchRegexpQuery_$1_init(OrgApacheLuceneSearchRegexpQuery_$1 *self);

__attribute__((unused)) static OrgApacheLuceneSearchRegexpQuery_$1 *new_OrgApacheLuceneSearchRegexpQuery_$1_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchRegexpQuery_$1)

J2OBJC_INITIALIZED_DEFN(OrgApacheLuceneSearchRegexpQuery)

@implementation OrgApacheLuceneSearchRegexpQuery

- (instancetype)initWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term {
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_(self, term);
  return self;
}

- (instancetype)initWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term
                                         withInt:(jint)flags {
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_(self, term, flags);
  return self;
}

- (instancetype)initWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term
                                         withInt:(jint)flags
                                         withInt:(jint)maxDeterminizedStates {
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withInt_(self, term, flags, maxDeterminizedStates);
  return self;
}

- (instancetype)initWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term
                                         withInt:(jint)flags
withOrgApacheLuceneUtilAutomatonAutomatonProvider:(id<OrgApacheLuceneUtilAutomatonAutomatonProvider>)provider
                                         withInt:(jint)maxDeterminizedStates {
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withOrgApacheLuceneUtilAutomatonAutomatonProvider_withInt_(self, term, flags, provider, maxDeterminizedStates);
  return self;
}

- (NSString *)toStringWithNSString:(NSString *)field {
  JavaLangStringBuilder *buffer = [new_JavaLangStringBuilder_init() autorelease];
  if (![((NSString *) nil_chk([((OrgApacheLuceneIndexTerm *) nil_chk(term_)) field])) isEqual:field]) {
    [buffer appendWithNSString:[term_ field]];
    [buffer appendWithNSString:@":"];
  }
  [buffer appendWithChar:'/'];
  [buffer appendWithNSString:[term_ text]];
  [buffer appendWithChar:'/'];
  [buffer appendWithNSString:OrgApacheLuceneUtilToStringUtils_boostWithFloat_([self getBoost])];
  return [buffer description];
}

+ (void)initialize {
  if (self == [OrgApacheLuceneSearchRegexpQuery class]) {
    JreStrongAssignAndConsume(&OrgApacheLuceneSearchRegexpQuery_defaultProvider_, new_OrgApacheLuceneSearchRegexpQuery_$1_init());
    J2OBJC_SET_INITIALIZED(OrgApacheLuceneSearchRegexpQuery)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgApacheLuceneIndexTerm:", "RegexpQuery", NULL, 0x1, NULL, NULL },
    { "initWithOrgApacheLuceneIndexTerm:withInt:", "RegexpQuery", NULL, 0x1, NULL, NULL },
    { "initWithOrgApacheLuceneIndexTerm:withInt:withInt:", "RegexpQuery", NULL, 0x1, NULL, NULL },
    { "initWithOrgApacheLuceneIndexTerm:withInt:withOrgApacheLuceneUtilAutomatonAutomatonProvider:withInt:", "RegexpQuery", NULL, 0x1, NULL, NULL },
    { "toStringWithNSString:", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "defaultProvider_", NULL, 0xa, "Lorg.apache.lucene.util.automaton.AutomatonProvider;", &OrgApacheLuceneSearchRegexpQuery_defaultProvider_, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchRegexpQuery = { 2, "RegexpQuery", "org.apache.lucene.search", NULL, 0x1, 5, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneSearchRegexpQuery;
}

@end

void OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_(OrgApacheLuceneSearchRegexpQuery *self, OrgApacheLuceneIndexTerm *term) {
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_(self, term, OrgApacheLuceneUtilAutomatonRegExp_ALL);
}

OrgApacheLuceneSearchRegexpQuery *new_OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_(OrgApacheLuceneIndexTerm *term) {
  OrgApacheLuceneSearchRegexpQuery *self = [OrgApacheLuceneSearchRegexpQuery alloc];
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_(self, term);
  return self;
}

void OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_(OrgApacheLuceneSearchRegexpQuery *self, OrgApacheLuceneIndexTerm *term, jint flags) {
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withOrgApacheLuceneUtilAutomatonAutomatonProvider_withInt_(self, term, flags, OrgApacheLuceneSearchRegexpQuery_defaultProvider_, OrgApacheLuceneUtilAutomatonOperations_DEFAULT_MAX_DETERMINIZED_STATES);
}

OrgApacheLuceneSearchRegexpQuery *new_OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_(OrgApacheLuceneIndexTerm *term, jint flags) {
  OrgApacheLuceneSearchRegexpQuery *self = [OrgApacheLuceneSearchRegexpQuery alloc];
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_(self, term, flags);
  return self;
}

void OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withInt_(OrgApacheLuceneSearchRegexpQuery *self, OrgApacheLuceneIndexTerm *term, jint flags, jint maxDeterminizedStates) {
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withOrgApacheLuceneUtilAutomatonAutomatonProvider_withInt_(self, term, flags, OrgApacheLuceneSearchRegexpQuery_defaultProvider_, maxDeterminizedStates);
}

OrgApacheLuceneSearchRegexpQuery *new_OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withInt_(OrgApacheLuceneIndexTerm *term, jint flags, jint maxDeterminizedStates) {
  OrgApacheLuceneSearchRegexpQuery *self = [OrgApacheLuceneSearchRegexpQuery alloc];
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withInt_(self, term, flags, maxDeterminizedStates);
  return self;
}

void OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withOrgApacheLuceneUtilAutomatonAutomatonProvider_withInt_(OrgApacheLuceneSearchRegexpQuery *self, OrgApacheLuceneIndexTerm *term, jint flags, id<OrgApacheLuceneUtilAutomatonAutomatonProvider> provider, jint maxDeterminizedStates) {
  OrgApacheLuceneSearchAutomatonQuery_initWithOrgApacheLuceneIndexTerm_withOrgApacheLuceneUtilAutomatonAutomaton_withInt_(self, term, [((OrgApacheLuceneUtilAutomatonRegExp *) [new_OrgApacheLuceneUtilAutomatonRegExp_initWithNSString_withInt_([((OrgApacheLuceneIndexTerm *) nil_chk(term)) text], flags) autorelease]) toAutomatonWithOrgApacheLuceneUtilAutomatonAutomatonProvider:provider withInt:maxDeterminizedStates], maxDeterminizedStates);
}

OrgApacheLuceneSearchRegexpQuery *new_OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withOrgApacheLuceneUtilAutomatonAutomatonProvider_withInt_(OrgApacheLuceneIndexTerm *term, jint flags, id<OrgApacheLuceneUtilAutomatonAutomatonProvider> provider, jint maxDeterminizedStates) {
  OrgApacheLuceneSearchRegexpQuery *self = [OrgApacheLuceneSearchRegexpQuery alloc];
  OrgApacheLuceneSearchRegexpQuery_initWithOrgApacheLuceneIndexTerm_withInt_withOrgApacheLuceneUtilAutomatonAutomatonProvider_withInt_(self, term, flags, provider, maxDeterminizedStates);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchRegexpQuery)

@implementation OrgApacheLuceneSearchRegexpQuery_$1

- (OrgApacheLuceneUtilAutomatonAutomaton *)getAutomatonWithNSString:(NSString *)name {
  return nil;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneSearchRegexpQuery_$1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getAutomatonWithNSString:", "getAutomaton", "Lorg.apache.lucene.util.automaton.Automaton;", 0x1, NULL, NULL },
    { "init", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchRegexpQuery_$1 = { 2, "", "org.apache.lucene.search", "RegexpQuery", 0x8008, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneSearchRegexpQuery_$1;
}

@end

void OrgApacheLuceneSearchRegexpQuery_$1_init(OrgApacheLuceneSearchRegexpQuery_$1 *self) {
  NSObject_init(self);
}

OrgApacheLuceneSearchRegexpQuery_$1 *new_OrgApacheLuceneSearchRegexpQuery_$1_init() {
  OrgApacheLuceneSearchRegexpQuery_$1 *self = [OrgApacheLuceneSearchRegexpQuery_$1 alloc];
  OrgApacheLuceneSearchRegexpQuery_$1_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchRegexpQuery_$1)
