//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./queryparser/src/java/org/apache/lucene/queryparser/xml/builders/SpanOrBuilder.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/queryparser/xml/builders/SpanOrBuilder.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder

- (instancetype)init {
  OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder = { 2, "SpanOrBuilder", "org.apache.lucene.queryparser.xml.builders", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder;
}

@end

void OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder_init(OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder *self) {
  NSObject_init(self);
}

OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder *new_OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder_init() {
  OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder *self = [OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder alloc];
  OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneQueryparserXmlBuildersSpanOrBuilder)
