//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/store/IndexInput.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneStoreIndexInput_INCLUDE_ALL")
#if OrgApacheLuceneStoreIndexInput_RESTRICT
#define OrgApacheLuceneStoreIndexInput_INCLUDE_ALL 0
#else
#define OrgApacheLuceneStoreIndexInput_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneStoreIndexInput_RESTRICT

#if !defined (_OrgApacheLuceneStoreIndexInput_) && (OrgApacheLuceneStoreIndexInput_INCLUDE_ALL || OrgApacheLuceneStoreIndexInput_INCLUDE)
#define _OrgApacheLuceneStoreIndexInput_

#define OrgApacheLuceneStoreDataInput_RESTRICT 1
#define OrgApacheLuceneStoreDataInput_INCLUDE 1
#include "org/apache/lucene/store/DataInput.h"

#define JavaIoCloseable_RESTRICT 1
#define JavaIoCloseable_INCLUDE 1
#include "java/io/Closeable.h"

@protocol OrgApacheLuceneStoreRandomAccessInput;

@interface OrgApacheLuceneStoreIndexInput : OrgApacheLuceneStoreDataInput < NSCopying, JavaIoCloseable >

#pragma mark Public

- (OrgApacheLuceneStoreIndexInput *)clone;

- (void)close;

- (jlong)getFilePointer;

- (jlong)length;

- (id<OrgApacheLuceneStoreRandomAccessInput>)randomAccessSliceWithLong:(jlong)offset
                                                              withLong:(jlong)length;

- (void)seekWithLong:(jlong)pos;

- (OrgApacheLuceneStoreIndexInput *)sliceWithNSString:(NSString *)sliceDescription
                                             withLong:(jlong)offset
                                             withLong:(jlong)length;

- (NSString *)description;

#pragma mark Protected

- (instancetype)initWithNSString:(NSString *)resourceDescription;

- (NSString *)getFullSliceDescriptionWithNSString:(NSString *)sliceDescription;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneStoreIndexInput)

FOUNDATION_EXPORT void OrgApacheLuceneStoreIndexInput_initWithNSString_(OrgApacheLuceneStoreIndexInput *self, NSString *resourceDescription);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneStoreIndexInput)

#endif

#pragma pop_macro("OrgApacheLuceneStoreIndexInput_INCLUDE_ALL")
