//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/sinks/TeeSinkTokenFilter.java
//

#include "J2ObjC_source.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/ref/WeakReference.h"
#include "java/util/Iterator.h"
#include "java/util/LinkedList.h"
#include "java/util/List.h"
#include "org/apache/lucene/analysis/TokenFilter.h"
#include "org/apache/lucene/analysis/TokenStream.h"
#include "org/apache/lucene/analysis/sinks/TeeSinkTokenFilter.h"
#include "org/apache/lucene/util/AttributeFactory.h"
#include "org/apache/lucene/util/AttributeImpl.h"
#include "org/apache/lucene/util/AttributeSource.h"

#if __has_feature(objc_arc)
#error "org/apache/lucene/analysis/sinks/TeeSinkTokenFilter must not be compiled with ARC (-fobjc-arc)"
#endif

@interface OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter () {
 @public
  id<JavaUtilList> sinks_;
}

@end

J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter, sinks_, id<JavaUtilList>)

inline OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_get_ACCEPT_ALL_FILTER(void);
static OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_ACCEPT_ALL_FILTER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter, ACCEPT_ALL_FILTER, OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *)

@interface OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream () {
 @public
  id<JavaUtilList> cachedStates_;
  OrgApacheLuceneUtilAttributeSource_State *finalState_;
  id<JavaUtilIterator> it_;
  OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *filter_;
}

- (instancetype)initWithOrgApacheLuceneUtilAttributeSource:(OrgApacheLuceneUtilAttributeSource *)source
withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter:(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *)filter;

- (jboolean)acceptWithOrgApacheLuceneUtilAttributeSource:(OrgApacheLuceneUtilAttributeSource *)source;

- (void)addStateWithOrgApacheLuceneUtilAttributeSource_State:(OrgApacheLuceneUtilAttributeSource_State *)state;

- (void)setFinalStateWithOrgApacheLuceneUtilAttributeSource_State:(OrgApacheLuceneUtilAttributeSource_State *)finalState;

@end

J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream, cachedStates_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream, finalState_, OrgApacheLuceneUtilAttributeSource_State *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream, it_, id<JavaUtilIterator>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream, filter_, OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *)

__attribute__((unused)) static void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *self, OrgApacheLuceneUtilAttributeSource *source, OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *filter);

__attribute__((unused)) static OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *new_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_(OrgApacheLuceneUtilAttributeSource *source, OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *filter) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *create_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_(OrgApacheLuceneUtilAttributeSource *source, OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *filter);

__attribute__((unused)) static jboolean OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_acceptWithOrgApacheLuceneUtilAttributeSource_(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *self, OrgApacheLuceneUtilAttributeSource *source);

__attribute__((unused)) static void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_addStateWithOrgApacheLuceneUtilAttributeSource_State_(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *self, OrgApacheLuceneUtilAttributeSource_State *state);

__attribute__((unused)) static void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_setFinalStateWithOrgApacheLuceneUtilAttributeSource_State_(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *self, OrgApacheLuceneUtilAttributeSource_State *finalState);

@interface OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1 : OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter

- (instancetype)init;

- (jboolean)acceptWithOrgApacheLuceneUtilAttributeSource:(OrgApacheLuceneUtilAttributeSource *)source;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1)

__attribute__((unused)) static void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1_init(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1 *self);

__attribute__((unused)) static OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1 *new_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1 *create_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1_init(void);

J2OBJC_INITIALIZED_DEFN(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter)

@implementation OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter

- (instancetype)initWithOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)input {
  OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_initWithOrgApacheLuceneAnalysisTokenStream_(self, input);
  return self;
}

- (OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *)newSinkTokenStream {
  return [self newSinkTokenStreamWithOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter:OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_ACCEPT_ALL_FILTER];
}

- (OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *)newSinkTokenStreamWithOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter:(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *)filter {
  OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *sink = create_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_([self cloneAttributes], filter);
  [((id<JavaUtilList>) nil_chk(self->sinks_)) addWithId:create_JavaLangRefWeakReference_initWithId_(sink)];
  return sink;
}

- (void)addSinkTokenStreamWithOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream:(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *)sink {
  if (![((OrgApacheLuceneUtilAttributeFactory *) nil_chk([self getAttributeFactory])) isEqual:[((OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *) nil_chk(sink)) getAttributeFactory]]) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"The supplied sink is not compatible to this tee");
  }
  for (id<JavaUtilIterator> it = JreRetainedLocalValue([((OrgApacheLuceneUtilAttributeSource *) nil_chk([self cloneAttributes])) getAttributeImplsIterator]); [((id<JavaUtilIterator>) nil_chk(it)) hasNext]; ) {
    [sink addAttributeImplWithOrgApacheLuceneUtilAttributeImpl:[it next]];
  }
  [((id<JavaUtilList>) nil_chk(self->sinks_)) addWithId:create_JavaLangRefWeakReference_initWithId_(sink)];
}

- (void)consumeAllTokens {
  while ([self incrementToken]) {
  }
}

- (jboolean)incrementToken {
  if ([((OrgApacheLuceneAnalysisTokenStream *) nil_chk(input_)) incrementToken]) {
    OrgApacheLuceneUtilAttributeSource_State *state = nil;
    for (JavaLangRefWeakReference * __strong ref in nil_chk(sinks_)) {
      OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *sink = [((JavaLangRefWeakReference *) nil_chk(ref)) get];
      if (sink != nil) {
        if (OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_acceptWithOrgApacheLuceneUtilAttributeSource_(sink, self)) {
          if (state == nil) {
            state = [self captureState];
          }
          OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_addStateWithOrgApacheLuceneUtilAttributeSource_State_(sink, state);
        }
      }
    }
    return true;
  }
  return false;
}

- (void)end {
  [super end];
  OrgApacheLuceneUtilAttributeSource_State *finalState = JreRetainedLocalValue([self captureState]);
  for (JavaLangRefWeakReference * __strong ref in nil_chk(sinks_)) {
    OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *sink = [((JavaLangRefWeakReference *) nil_chk(ref)) get];
    if (sink != nil) {
      OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_setFinalStateWithOrgApacheLuceneUtilAttributeSource_State_(sink, finalState);
    }
  }
}

- (void)dealloc {
  RELEASE_(sinks_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 5, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, 5, -1, -1, -1 },
    { NULL, "V", 0x11, -1, -1, 5, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithOrgApacheLuceneAnalysisTokenStream:);
  methods[1].selector = @selector(newSinkTokenStream);
  methods[2].selector = @selector(newSinkTokenStreamWithOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter:);
  methods[3].selector = @selector(addSinkTokenStreamWithOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream:);
  methods[4].selector = @selector(consumeAllTokens);
  methods[5].selector = @selector(incrementToken);
  methods[6].selector = @selector(end);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "sinks_", "LJavaUtilList;", .constantValue.asLong = 0, 0x12, -1, -1, 6, -1 },
    { "ACCEPT_ALL_FILTER", "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter;", .constantValue.asLong = 0, 0x1a, -1, 7, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneAnalysisTokenStream;", "newSinkTokenStream", "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter;", "addSinkTokenStream", "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream;", "LJavaIoIOException;", "Ljava/util/List<Ljava/lang/ref/WeakReference<Lorg/apache/lucene/analysis/sinks/TeeSinkTokenFilter$SinkTokenStream;>;>;", &OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_ACCEPT_ALL_FILTER, "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter;LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream;" };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter = { "TeeSinkTokenFilter", "org.apache.lucene.analysis.sinks", ptrTable, methods, fields, 7, 0x11, 7, 2, -1, 8, -1, -1, -1 };
  return &_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter;
}

+ (void)initialize {
  if (self == [OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter class]) {
    JreStrongAssignAndConsume(&OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_ACCEPT_ALL_FILTER, new_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1_init());
    J2OBJC_SET_INITIALIZED(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter)
  }
}

@end

void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_initWithOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter *self, OrgApacheLuceneAnalysisTokenStream *input) {
  OrgApacheLuceneAnalysisTokenFilter_initWithOrgApacheLuceneAnalysisTokenStream_(self, input);
  JreStrongAssignAndConsume(&self->sinks_, new_JavaUtilLinkedList_init());
}

OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter *new_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_initWithOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisTokenStream *input) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter, initWithOrgApacheLuceneAnalysisTokenStream_, input)
}

OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter *create_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_initWithOrgApacheLuceneAnalysisTokenStream_(OrgApacheLuceneAnalysisTokenStream *input) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter, initWithOrgApacheLuceneAnalysisTokenStream_, input)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter)

@implementation OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jboolean)acceptWithOrgApacheLuceneUtilAttributeSource:(OrgApacheLuceneUtilAttributeSource *)source {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)reset {
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(acceptWithOrgApacheLuceneUtilAttributeSource:);
  methods[2].selector = @selector(reset);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "accept", "LOrgApacheLuceneUtilAttributeSource;", "LJavaIoIOException;", "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter;" };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter = { "SinkFilter", "org.apache.lucene.analysis.sinks", ptrTable, methods, NULL, 7, 0x409, 3, 0, 3, -1, -1, -1, -1 };
  return &_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter;
}

@end

void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_init(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter)

@implementation OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream

- (instancetype)initWithOrgApacheLuceneUtilAttributeSource:(OrgApacheLuceneUtilAttributeSource *)source
withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter:(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *)filter {
  OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_(self, source, filter);
  return self;
}

- (jboolean)acceptWithOrgApacheLuceneUtilAttributeSource:(OrgApacheLuceneUtilAttributeSource *)source {
  return OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_acceptWithOrgApacheLuceneUtilAttributeSource_(self, source);
}

- (void)addStateWithOrgApacheLuceneUtilAttributeSource_State:(OrgApacheLuceneUtilAttributeSource_State *)state {
  OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_addStateWithOrgApacheLuceneUtilAttributeSource_State_(self, state);
}

- (void)setFinalStateWithOrgApacheLuceneUtilAttributeSource_State:(OrgApacheLuceneUtilAttributeSource_State *)finalState {
  OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_setFinalStateWithOrgApacheLuceneUtilAttributeSource_State_(self, finalState);
}

- (jboolean)incrementToken {
  if (it_ == nil) {
    JreStrongAssign(&it_, [((id<JavaUtilList>) nil_chk(cachedStates_)) iterator]);
  }
  if (![((id<JavaUtilIterator>) nil_chk(it_)) hasNext]) {
    return false;
  }
  OrgApacheLuceneUtilAttributeSource_State *state = JreRetainedLocalValue([((id<JavaUtilIterator>) nil_chk(it_)) next]);
  [self restoreStateWithOrgApacheLuceneUtilAttributeSource_State:state];
  return true;
}

- (void)end {
  if (finalState_ != nil) {
    [self restoreStateWithOrgApacheLuceneUtilAttributeSource_State:finalState_];
  }
}

- (void)reset {
  JreStrongAssign(&it_, [((id<JavaUtilList>) nil_chk(cachedStates_)) iterator]);
}

- (void)dealloc {
  RELEASE_(cachedStates_);
  RELEASE_(finalState_);
  RELEASE_(it_);
  RELEASE_(filter_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, -1, -1, -1 },
    { NULL, "Z", 0x2, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 5, 4, -1, -1, -1, -1 },
    { NULL, "Z", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x11, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithOrgApacheLuceneUtilAttributeSource:withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter:);
  methods[1].selector = @selector(acceptWithOrgApacheLuceneUtilAttributeSource:);
  methods[2].selector = @selector(addStateWithOrgApacheLuceneUtilAttributeSource_State:);
  methods[3].selector = @selector(setFinalStateWithOrgApacheLuceneUtilAttributeSource_State:);
  methods[4].selector = @selector(incrementToken);
  methods[5].selector = @selector(end);
  methods[6].selector = @selector(reset);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "cachedStates_", "LJavaUtilList;", .constantValue.asLong = 0, 0x12, -1, -1, 6, -1 },
    { "finalState_", "LOrgApacheLuceneUtilAttributeSource_State;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "it_", "LJavaUtilIterator;", .constantValue.asLong = 0, 0x2, -1, -1, 7, -1 },
    { "filter_", "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneUtilAttributeSource;LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter;", "accept", "LOrgApacheLuceneUtilAttributeSource;", "addState", "LOrgApacheLuceneUtilAttributeSource_State;", "setFinalState", "Ljava/util/List<Lorg/apache/lucene/util/AttributeSource$State;>;", "Ljava/util/Iterator<Lorg/apache/lucene/util/AttributeSource$State;>;", "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter;" };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream = { "SinkTokenStream", "org.apache.lucene.analysis.sinks", ptrTable, methods, fields, 7, 0x19, 7, 4, 8, -1, -1, -1, -1 };
  return &_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream;
}

@end

void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *self, OrgApacheLuceneUtilAttributeSource *source, OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *filter) {
  OrgApacheLuceneAnalysisTokenStream_initWithOrgApacheLuceneUtilAttributeSource_(self, source);
  JreStrongAssignAndConsume(&self->cachedStates_, new_JavaUtilLinkedList_init());
  JreStrongAssign(&self->it_, nil);
  JreStrongAssign(&self->filter_, filter);
}

OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *new_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_(OrgApacheLuceneUtilAttributeSource *source, OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *filter) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream, initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_, source, filter)
}

OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *create_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_(OrgApacheLuceneUtilAttributeSource *source, OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *filter) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream, initWithOrgApacheLuceneUtilAttributeSource_withOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_, source, filter)
}

jboolean OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_acceptWithOrgApacheLuceneUtilAttributeSource_(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *self, OrgApacheLuceneUtilAttributeSource *source) {
  return [((OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter *) nil_chk(self->filter_)) acceptWithOrgApacheLuceneUtilAttributeSource:source];
}

void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_addStateWithOrgApacheLuceneUtilAttributeSource_State_(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *self, OrgApacheLuceneUtilAttributeSource_State *state) {
  if (self->it_ != nil) {
    @throw create_JavaLangIllegalStateException_initWithNSString_(@"The tee must be consumed before sinks are consumed.");
  }
  [((id<JavaUtilList>) nil_chk(self->cachedStates_)) addWithId:state];
}

void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream_setFinalStateWithOrgApacheLuceneUtilAttributeSource_State_(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream *self, OrgApacheLuceneUtilAttributeSource_State *finalState) {
  JreStrongAssign(&self->finalState_, finalState);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkTokenStream)

@implementation OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jboolean)acceptWithOrgApacheLuceneUtilAttributeSource:(OrgApacheLuceneUtilAttributeSource *)source {
  return true;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(acceptWithOrgApacheLuceneUtilAttributeSource:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "accept", "LOrgApacheLuceneUtilAttributeSource;", "LOrgApacheLuceneAnalysisSinksTeeSinkTokenFilter;" };
  static const J2ObjcClassInfo _OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1 = { "", "org.apache.lucene.analysis.sinks", ptrTable, methods, NULL, 7, 0x8018, 2, 0, 2, -1, -1, -1, -1 };
  return &_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1;
}

@end

void OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1_init(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1 *self) {
  OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_SinkFilter_init(self);
}

OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1 *new_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1_init() {
  J2OBJC_NEW_IMPL(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1, init)
}

OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1 *create_OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1_init() {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneAnalysisSinksTeeSinkTokenFilter_1, init)
}
