//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/codecs/compressing/Decompressor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneCodecsCompressingDecompressor")
#ifdef RESTRICT_OrgApacheLuceneCodecsCompressingDecompressor
#define INCLUDE_ALL_OrgApacheLuceneCodecsCompressingDecompressor 0
#else
#define INCLUDE_ALL_OrgApacheLuceneCodecsCompressingDecompressor 1
#endif
#undef RESTRICT_OrgApacheLuceneCodecsCompressingDecompressor

#if !defined (OrgApacheLuceneCodecsCompressingDecompressor_) && (INCLUDE_ALL_OrgApacheLuceneCodecsCompressingDecompressor || defined(INCLUDE_OrgApacheLuceneCodecsCompressingDecompressor))
#define OrgApacheLuceneCodecsCompressingDecompressor_

@class OrgApacheLuceneStoreDataInput;
@class OrgApacheLuceneUtilBytesRef;

/*!
 @brief A decompressor.
 */
@interface OrgApacheLuceneCodecsCompressingDecompressor : NSObject < NSCopying >

#pragma mark Public

- (OrgApacheLuceneCodecsCompressingDecompressor *)clone;

/*!
 @brief Decompress bytes that were stored between offsets <code>offset</code> and
 <code>offset+length</code> in the original stream from the compressed
 stream <code>in</code> to <code>bytes</code>.
 After returning, the length
 of <code>bytes</code> (<code>bytes.length</code>) must be equal to
 <code>length</code>. Implementations of this method are free to resize
 <code>bytes</code> depending on their needs.
 @param inArg the input that stores the compressed stream
 @param originalLength the length of the original data (before compression)
 @param offset bytes before this offset do not need to be decompressed
 @param length bytes after <code>offset+length</code> do not need to be decompressed
 @param bytes a <code>BytesRef</code> where to store the decompressed data
 */
- (void)decompressWithOrgApacheLuceneStoreDataInput:(OrgApacheLuceneStoreDataInput *)inArg
                                            withInt:(jint)originalLength
                                            withInt:(jint)offset
                                            withInt:(jint)length
                    withOrgApacheLuceneUtilBytesRef:(OrgApacheLuceneUtilBytesRef *)bytes;

#pragma mark Protected

/*!
 @brief Sole constructor, typically called from sub-classes.
 */
- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneCodecsCompressingDecompressor)

FOUNDATION_EXPORT void OrgApacheLuceneCodecsCompressingDecompressor_init(OrgApacheLuceneCodecsCompressingDecompressor *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneCodecsCompressingDecompressor)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneCodecsCompressingDecompressor")
