//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/shingle/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneAnalysisShinglePackage_info_INCLUDE_ALL")
#if OrgApacheLuceneAnalysisShinglePackage_info_RESTRICT
#define OrgApacheLuceneAnalysisShinglePackage_info_INCLUDE_ALL 0
#else
#define OrgApacheLuceneAnalysisShinglePackage_info_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneAnalysisShinglePackage_info_RESTRICT

#pragma pop_macro("OrgApacheLuceneAnalysisShinglePackage_info_INCLUDE_ALL")
