//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/codecs/lucene50/package-info.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/codecs/lucene50/package-info.h"

#if __has_feature(objc_arc)
#error "org/apache/lucene/codecs/lucene50/package-info must not be compiled with ARC (-fobjc-arc)"
#endif
