//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./queryparser/src/java/org/apache/lucene/queryparser/flexible/messages/Message.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/queryparser/flexible/messages/Message.h"

#pragma clang diagnostic ignored "-Wprotocol"

@interface OrgApacheLuceneQueryparserFlexibleMessagesMessage : NSObject

@end

@implementation OrgApacheLuceneQueryparserFlexibleMessagesMessage

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _OrgApacheLuceneQueryparserFlexibleMessagesMessage = { 2, "Message", "org.apache.lucene.queryparser.flexible.messages", NULL, 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheLuceneQueryparserFlexibleMessagesMessage;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheLuceneQueryparserFlexibleMessagesMessage)
