//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./core/src/java/org/apache/lucene/search/QueryCache.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneSearchQueryCache_INCLUDE_ALL")
#if OrgApacheLuceneSearchQueryCache_RESTRICT
#define OrgApacheLuceneSearchQueryCache_INCLUDE_ALL 0
#else
#define OrgApacheLuceneSearchQueryCache_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneSearchQueryCache_RESTRICT

#if !defined (_OrgApacheLuceneSearchQueryCache_) && (OrgApacheLuceneSearchQueryCache_INCLUDE_ALL || OrgApacheLuceneSearchQueryCache_INCLUDE)
#define _OrgApacheLuceneSearchQueryCache_

@class OrgApacheLuceneSearchWeight;
@protocol OrgApacheLuceneSearchQueryCachingPolicy;

@protocol OrgApacheLuceneSearchQueryCache < NSObject, JavaObject >

- (OrgApacheLuceneSearchWeight *)doCacheWithOrgApacheLuceneSearchWeight:(OrgApacheLuceneSearchWeight *)weight
                            withOrgApacheLuceneSearchQueryCachingPolicy:(id<OrgApacheLuceneSearchQueryCachingPolicy>)policy;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchQueryCache)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchQueryCache)

#endif

#pragma pop_macro("OrgApacheLuceneSearchQueryCache_INCLUDE_ALL")
