//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./analysis/common/src/java/org/apache/lucene/analysis/de/GermanStemFilter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgApacheLuceneAnalysisDeGermanStemFilter_INCLUDE_ALL")
#if OrgApacheLuceneAnalysisDeGermanStemFilter_RESTRICT
#define OrgApacheLuceneAnalysisDeGermanStemFilter_INCLUDE_ALL 0
#else
#define OrgApacheLuceneAnalysisDeGermanStemFilter_INCLUDE_ALL 1
#endif
#undef OrgApacheLuceneAnalysisDeGermanStemFilter_RESTRICT

#if !defined (_OrgApacheLuceneAnalysisDeGermanStemFilter_) && (OrgApacheLuceneAnalysisDeGermanStemFilter_INCLUDE_ALL || OrgApacheLuceneAnalysisDeGermanStemFilter_INCLUDE)
#define _OrgApacheLuceneAnalysisDeGermanStemFilter_

#define OrgApacheLuceneAnalysisTokenFilter_RESTRICT 1
#define OrgApacheLuceneAnalysisTokenFilter_INCLUDE 1
#include "org/apache/lucene/analysis/TokenFilter.h"

@interface OrgApacheLuceneAnalysisDeGermanStemFilter : OrgApacheLuceneAnalysisTokenFilter

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneAnalysisDeGermanStemFilter)

FOUNDATION_EXPORT void OrgApacheLuceneAnalysisDeGermanStemFilter_init(OrgApacheLuceneAnalysisDeGermanStemFilter *self);

FOUNDATION_EXPORT OrgApacheLuceneAnalysisDeGermanStemFilter *new_OrgApacheLuceneAnalysisDeGermanStemFilter_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneAnalysisDeGermanStemFilter)

#endif

#pragma pop_macro("OrgApacheLuceneAnalysisDeGermanStemFilter_INCLUDE_ALL")
