//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./suggest/src/java/org/apache/lucene/search/spell/HighFrequencyDictionary.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/search/spell/HighFrequencyDictionary.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation OrgApacheLuceneSearchSpellHighFrequencyDictionary

- (instancetype)init {
  OrgApacheLuceneSearchSpellHighFrequencyDictionary_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const char *inner_classes[] = {"Lorg.apache.lucene.search.spell.HighFrequencyDictionary$HighFrequencyIterator;"};
  static const J2ObjcClassInfo _OrgApacheLuceneSearchSpellHighFrequencyDictionary = { 2, "HighFrequencyDictionary", "org.apache.lucene.search.spell", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_OrgApacheLuceneSearchSpellHighFrequencyDictionary;
}

@end

void OrgApacheLuceneSearchSpellHighFrequencyDictionary_init(OrgApacheLuceneSearchSpellHighFrequencyDictionary *self) {
  NSObject_init(self);
}

OrgApacheLuceneSearchSpellHighFrequencyDictionary *new_OrgApacheLuceneSearchSpellHighFrequencyDictionary_init() {
  OrgApacheLuceneSearchSpellHighFrequencyDictionary *self = [OrgApacheLuceneSearchSpellHighFrequencyDictionary alloc];
  OrgApacheLuceneSearchSpellHighFrequencyDictionary_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchSpellHighFrequencyDictionary)
